### ISSUE TITLE
Some tabs won't suspend (v0.1.2) [FF 58b16]

### ISSUE THREAD

**Issue by irvinm** [rNeomy/auto-tab-discard#1]
1. Configure the add-on to suspend all tabs for all reasons.
2. Set timeout to 10 seconds for testing purposes.
3. Open:  https://www.newegg.com/ 
4. Open:  https://www.yahoo.com/news/ 
5. Open:  https://github.com/rNeomy/auto-tab-discard
6. Notice that none of them suspend even if done manually.

![options](https://user-images.githubusercontent.com/979729/34907604-437a82a2-f84f-11e7-8719-c42607f8d227.PNG)

**Comment by irvinm** [comment]
I've been playing around with this more and it doesn't seem to be consistent.  There are times I can reload the page manually and it discards properly after 10 seconds.  There are other times after a reload that it will never discard.  I'll continue to evaluate patterns.

In my recent testing, it does appear that I am able to manually discard the tab even when it won't discard after the timeout.

**Comment by irvinm** [comment]
Ok, so I think I have found a pattern.

In this animated gif:

- I start with loaded tabs that are not sleeping
- I click on each tab, reload, and wait till the page completely loads
- Notice then each tab successfully sleeps after 10 seconds
- Now, I click on each tab to reload and before the page reloads completely I click off of the tab
- Notice now that each tab will not sleep
- I finally repeat the original process by reloading the tab and waiting until the page completely loads
- Tabs then sleep successfully again. 

![2018-01-19_10-15-28](https://user-images.githubusercontent.com/979729/35157841-3c32e9ea-fd03-11e7-9973-cb4e4b7b59a0.gif)

**Comment by rNeomy** [comment]
Thanks for the report. It is fixed on 0.1.3. Nice catch!

**Comment by mysterix01** [comment]
It doesn't work on cuurent Firefox 58 stable. Are you aware of the problem?

**Comment by rayman89** [comment]
Is not a bug is access to an api that was recently introduced would be available on firefox 59 stable if Im not mistaken.

**Comment by rNeomy** [comment]
Yap! The extension min version is changed to FF 59. No way to fix the internal APIs when they are buggy.

**Comment by irvinm** [comment]
FF58 is definitely buggy with tab discarding as everything is working great in FF59b3.

Also, as a quick update on this issue, the change definitely works better but there is still an edge case that is very minor and not worth reopening the bug.

If (for example) I am on this page and simple right-click on each example URL and "Open Link in New Tab", those resulting tabs will not "discard" until they are "clicked on \ made active" at least once.  Definitely an edge case and only a minor inconvenience.
