### ISSUE TITLE
Auto Tab Discard kills Firefox's addon manager (Conflict with Tree Style Tab?)

### ISSUE THREAD

**Issue by dksher** [rNeomy/auto-tab-discard#100]
Today I installed `Tree Style Tab 3.1.2` to my Firefox 67.0.4, then installed `Auto Tab Discard 0.3.2`. I noticed any changes to the options of `Auto Tab Discard` didn't work at all, and the whole Firefox's addon manager died. No addons were listed in `about:addons`, "Get Add-ons" page was blank and I couldn't uninstall addons from the toolbar icons.

The only way to solve the situation I found was to restart Firefox as Safe Mode, disable `Tree Style Tab`, restart Firefox and uninstall `Auto Tab Discard`.

I guess `Auto Tab Discard` conflict with `Tree Style Tab`?

**Comment by JeroU** [comment]
i have nearly the same behaviour:
- Mageia Cauldron
- Firefox 68.2.0esr (64 bits)
- Auto Tab Discard 0.3.2.1
- TreeStyleTab 3.2.3 (2019.11.5)
~ 750 tabs
After a while (let's say 1 day), the extensions no longer works, firefox WebExtensions process use a full CPU and no new url can be loaded.
Removing auto tab discard "fix" the issue.

**Comment by grahamperrin** [comment]
@dksher @JeroU is this still an issue? 

Not an issue for me, with 128 extensions enabled (including Tree Style Tab).

**Comment by JeroU** [comment]
Well, i no longer user auto tab discard for a while.
I should give it a try again
Thanks

**Comment by RedPill-Neo** [comment]
well, what other extensions can I use other than auto tab discard?
