### ISSUE TITLE
Unchecked runtime.lastError: The message port closed before a response was received.

### ISSUE THREAD

**Issue by RiZKiT** [rNeomy/auto-tab-discard#101]
In Chrome 75 (on MacOS 10.14.5) I get the following error `Unchecked runtime.lastError: The message port closed before a response was received.` in the console after some seconds, and nearly on every tab switch. 

It seems only to happen on pinned tabs!

I do not get that error when I disable the extension.

Seems to be related to https://github.com/gatsbyjs/gatsby/issues/9899 and https://github.com/rNeomy/auto-tab-discard/issues/63.

**Comment by rNeomy** [comment]
Do you still have this issue? I believe it is already fixed

**Comment by RiZKiT** [comment]
Sadly it's still there, Plugin version 0.3.2 on Vivaldi (Chrome78), macOS Version 10.14.6

**Comment by rNeomy** [comment]
@RiZKiT at what line number?

**Comment by RiZKiT** [comment]
Ah well, version 0.3.3 seems to fix it. Wasn't yet available last time I answered.
