### ISSUE TITLE
Un-discard focused tab after configurable timeout

### ISSUE THREAD

**Issue by cspk** [rNeomy/auto-tab-discard#103]
If you have a bunch of discarded tabs and use keyboard to navigate tabs, it's frequent that you're starting to Ctrl-PgUp/Ctrl-PgDn through the discarded ones, waking up all of them. It would be really nice to have a configurable "wake up timeout" that determines a time (in milliseconds, for example) which you have to spend on a discarded tab before it gets un-discarded. The Great Suspender has similar stuff, but it's not configurable.

**Comment by rNeomy** [comment]
Unfortunately due to the API limitation, the only way to remove discarding at the moment is to focus a tab.
