### ISSUE TITLE
Difference with firefox 67 auto unloads tab

### ISSUE THREAD

**Issue by erotavlasme** [rNeomy/auto-tab-discard#104]
Hi,
[firefox since 67 auto unloads tabs](https://www.ghacks.net/2019/03/01/firefox-67-automatically-unload-unused-tabs-to-improve-memory/). What is the main differences with auto tab discard?
Thank you

**Comment by Grossdm** [comment]
I have not seen much documentation on Firefox's native tab unloading.

That said, [Auto Tab Discard](../) has an option to not unload tabs with unsubmitted form data, for example.
I do have some uncertainty with its whitelist, which is called "Exceptions".
In general, it's helpful.
