### ISSUE TITLE
Security Risk? "This extension may have been corrupted"

### ISSUE THREAD

**Issue by Francewhoa** [rNeomy/auto-tab-discard#106]
## Summary

This ticket is to report 3 suspicious events with this extension for Chrome

## Steps to reproduce

1. Using Chrome 76 install "Auto Tab Discard" 0.3.2 from https://chrome.google.com/webstore/detail/auto-tab-discard/jhnleheckmknfcgijgkadoemagpecfol

1. Notice the suspicious permission "**Read and change all data on the websites that you visit**".
Screenshot attached. This is the first challenge.
![suspicious permission changed---Auto Tab Discard---2019-09-09---14:21:47---Selection_001---francois](https://user-images.githubusercontent.com/119942/64567807-f03bd780-d30d-11e9-86a1-620ae814b397.jpg)

1. Use Chrome for a while

1. Close Chrome

1. Re-open Chrome. Go to chrome://extensions/

1. This warning message is display: "**This extension may have been corrupted**"
This is the second challenge. Find attached screenshot.
![This extension may have been corrupted---Auto Tab Discard---2019-09-09---13:53:45---Extensions - Google Chrome_001---francewhoa](https://user-images.githubusercontent.com/119942/64567858-15304a80-d30e-11e9-8026-7ce7748f677c.jpg)

At URL it says the https://chrome.google.com/webstore/detail/auto-tab-discard/jhnleheckmknfcgijgkadoemagpecfol it read: "**Offered by: joue.quroi**". 
Expected result is "**Offered by: add0n.com**"? Per the author website at https://add0n.com/tab-discard.html
Archived page at http://archive.fo/9YjrL
This is the third challenge.

## Question

Is this warning message legit? "This extension may have been corrupted"
Is it safe to repair or reinstall this extension?

## Note

Those 3 challenges can not be reproduce with the Firefox version at https://addons.mozilla.org/en-US/firefox/addon/auto-tab-discard/

**Comment by rNeomy** [comment]
2. This extension injects a timer script into all webpages which potentially can read the website data. That is why you get this warning.

6. This one is suspicious, you should get this warning only when the downloaded extension gets modified locally.

> "Offered by: joue.quroi". Expected result is "Offered by: add0n.com"?

My developer id at Chrome is "joue.quroi". This extension is part of add0n.com's collection and gets reviewed internally.

> Is this warning message legit? "This extension may have been corrupted"

I would say your local files are being modified by another process or your Chrome installation is corrupted. Reinstall Chrome and switch to a new profile.

**Comment by rNeomy** [comment]
to be clear, this extension neither collects any data nor sends any metrics to any servers whatsoever.

**Comment by Francewhoa** [comment]
Thanks for your replies @rNeomy :)

I understand now that it's unlikely a security risk with this extension. But more likely a challenge somehow with the Chrome browser. 

I made no manual change to the auto-tab-discard extension. Also it's the stable version. Not a dev version manually installed. Maybe my Chrome crashed/exited while it was in the middle of writing to a file needed by auto-tab-discard. Such as auto-tab-discard's preference file(s) or some other file(s) required by auto-tab-discard. In turn, the file(s) would be in good faith "corrupted". In turn, after Chrome restart, it would automatically detect and trigger this message. "This extension may have been corrupted". Any how I'm happy to hear that it's more likely a challenge with Chrome browser. Not the extension.

**Comment by Luckz** [comment]
There are Chrome bugs that corrupt extensions. As a work-around you can open the Chrome store page to re-enable it without losing all your data.
