### ISSUE TITLE
Tabs never discard when "Do not discard tabs when computer is connected to a power source" is checked

### ISSUE THREAD

**Issue by dsedivec** [rNeomy/auto-tab-discard#107]
Steps to reproduce:

1. Install Auto Tab Discard in a fresh Firefox profile
2. Check "Do not discard tabs when computer is connected to a power source" option and save options
3. Disconnect computer from power source and wait until OS's battery widget displays a time remaining on battery power
4. Open a few tabs
5. Right click focused tab → Auto Tab Discard → Discard All Other Tabs

Expected behavior: All other tabs are discarded

Observed behavior: No tabs are discarded

Version info:
* 2019 MacBook Pro 15"
* macOS 10.14.6
* Firefox Developer Edition 70.0b6 (64-bit)
* Auto Tab Discard 0.3.2.1

Additional information:

If I uncheck "Do not discard tabs when computer is connected to a power source", save options, then "Discard All Other Tabs" again, all other tabs are discarded, as expected.

I opened Tools → Web Developer → Browser Console and confirmed that `BatteryManager.dischargingTime` is not returning `Infinity` (which I *assume* is important based on [this code][1]):

<img width="577" alt="image" src="https://user-images.githubusercontent.com/95333/64879377-76f8f900-d61b-11e9-888d-00de0fc137a3.png">

[1]: https://github.com/rNeomy/auto-tab-discard/blob/55797813e415fd59f86544176cab8c946b224755/data/inject/top.js#L65-L71

Thank you for writing/maintaining this extension!

**Comment by rNeomy** [comment]
Thanks for the report. Please reopen if it is not fixed by the next release.

**Comment by dsedivec** [comment]
OK, I apologize, I think I led you astray somehow.  Here's what I see from `getBattery` on my MacBook Pro, FF 71.0b8:

Power source | Charge level | `charging` | `dischargingTime`
---|------------|------------|---------------------
AC | 100% | `false` | `Infinity`
*AC* | *Less than 100%* | *`true`*\* | *`Infinity`*\*
Battery (just disconnected) | 100% | `false` | `Infinity`
Battery (disconnected more than a few minutes) | 100% | `false` | Integer, ex. `33360`

\* I didn't actually drain my battery below 100% tonight, so I'm just guessing what you'd get back when the laptop is actually charging.

I think you want to skip discarding the tab if `tools.battery` resolves to true, and `tools.battery` should only be true if the machine is on AC power, **so it seems like your original code of `dischargingTime === Infinity` should have worked**.

Instead, with the current code that checks `charging === True`, you only skip unloading tabs when the laptop is plugged in *and* it is actually charging the battery (i.e. battery level < 100%).  So right now, while I'm fully charged and on AC power with "Do not discard tabs when computer is connected to a power source" checked, tabs are being unloaded.

Am I making some basic logic error here?  I feel like I must be missing something.

I'm going to try changing the test back to `dischargingTime === Infinity` locally and test this again.  I'm going to be extra careful to leave the power unplugged long enough for `dischargingTime` to return an integer, too.  I'll report back.

**Comment by dsedivec** [comment]
* I cloned this repo
* I loaded the extension in Firefox with Add-ons → Debug Add-ons → Load Temporary Add-on
* I inserted `console.log(`\``${navigator.getBattery}`\``)` inside `tools.battery`

It logs `undefined` every time.  Am I missing something about extension development or permissions or something?  It seems like `top.js` doesn't have access to `navigator.getBattery`?

I can still call `navigator.getBattery` from the "Browser Console".

This is now Firefox Developer Edition 71.0b11 (64-bit) on macOS 10.14.6.

**Comment by rNeomy** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1313580
https://bugzilla.mozilla.org/show_bug.cgi?id=1314076

**Comment by rNeomy** [comment]
seems like there is no access to the API although it is supposed to by (1314076)[https://bugzilla.mozilla.org/show_bug.cgi?id=1314076)

**Comment by rNeomy** [comment]
Based on your observesions, I would say `b.charging === true || b.chargingTime !== Infinity` is a safe method to make sure the power is disconnected.
