### ISSUE TITLE
Discarded tab does not store youtube settings in video

### ISSUE THREAD

**Issue by marc-vdm** [rNeomy/auto-tab-discard#108]
When a paused youtube video gets discarded, settings like the playback time and playback speed are not stored.

**Comment by Screwtapello** [comment]
My understanding is that YouTube stores the playback time after X minutes of inactivity, and Auto Tab Discard discards the tab after Y minutes of inactivity. If Y < X, the tab is discarded after YouTube has a chance to save anything.

If I pause a YouTube video that I want to come back to later, I try to leave it as the active tab for a while (if I'm switching to a different app), or at least switch back to it occasionally to refresh the Auto Tab Discard's timer and give YouTube more of a chance to save.

I also bumped the discard timeout to 10 minutes (600 seconds), but I'm not sure if that was enough.

**Comment by trlkly** [comment]
I've had this problem all the time, too. YouTube doesn't seem to store the exact time--it always is a bit off. I would love a feature to save the YouTube time. 

However, I'm not sure that would really fit this extension, and that it wouldn't make more sense as a separate extension that could specialize in saving your place on YouTube and possibly other video sites.

**Comment by tdbe** [comment]
couldn't you append to the youtube url the current timestamp of the youtube video before discarding? Or do you not have permission for that in the extension?

**Comment by allanlaal** [comment]
I wound a workaround for this by also using this plugin: https://github.com/nkestrel/mediaurltimestamper

**Comment by rNeomy** [comment]
fixed in https://github.com/rNeomy/auto-tab-discard/issues/33
