### ISSUE TITLE
Doesn't play nice with Atlassian Jira

### ISSUE THREAD

**Issue by JamesFerguson** [rNeomy/auto-tab-discard#110]
So, this is probably more Jira's fault, but just in case I wanted to flag it here. FWIW, Jira is a popular ticket tracking system.

Jira does something custom (and probably hacky) with partially filled forms when they lose focus - or specifically when another field on the form gains focus. It seems to change them to disabled, under the hood it's changing the dom to replace a tree of divs (with attached events that present a wysiwyg editor and text entry component) with an input that has no type, a placeholder text saying your comment is unsaved and another attached event.

So because auto-tab-discard doesn't see a partially filled for it discards the tab and the comment gets lost.

Most likely this is something for Jira to do better, but I wanted to raise it in case there's something key in what they're doing that other sites might do too that auto-tab-discard could recognise and avoid discarding in that case.

Thanks for a great extension.

**Comment by Luckz** [comment]
You should just whitelist it, and their developers should support their app being discarded.
