### ISSUE TITLE
Translate into Korean

### ISSUE THREAD

**Issue by InnerPeaceKR** [rNeomy/auto-tab-discard#111]
I want to translate into Korean for this cool extension. Please add Korean on transifex. Thanks.

**Comment by rNeomy** [comment]
@InnerPeaceKR I think you need to send a request for Korean lang.

**Comment by InnerPeaceKR** [comment]
> 
> 
> @InnerPeaceKR I think you need to send a request for Korean lang.

I just sent a request

**Comment by rNeomy** [comment]
done! let me know when it should be merged. thanks!

**Comment by InnerPeaceKR** [comment]
I requested to join the team for Korean on transifex.

**Comment by rNeomy** [comment]
You should be part of the project on transifex now.

**Comment by InnerPeaceKR** [comment]
Translation completed. It's time to wait for update :)

**Comment by rNeomy** [comment]
Perfect! Please download the source code and give it a try to make sure everything looks good.

Firefox: about:debugging
Chrome: chrome://extensions
