### ISSUE TITLE
Support for Vivaldi

### ISSUE THREAD

**Issue by Erfesto** [rNeomy/auto-tab-discard#113]
(or its just a bug)

Great extension. so many options, but in Vivaldi (versions with Chromium 75+, who killed flag "automatic tab discarding"):

Tabs with exceptions ("tabs with the following hostnames are not being discarded") don't have protect (tested with vivaldi://discards).

Then i tested with "Disable automatic tab discarding" extension - "Auto tab discard" don't hibernate tabs, that must be hibernate (tabs without exceptions).

Then i tested "Disable automatic tab discarding" with other hibernate-extensions aka "The Great Discarder/The Great Suspender" - "Disable automatic tab discarding" dont' brake them...they works.

P.S
Sorry for bad english.

**Comment by rNeomy** [comment]
Please reopen if you are still experiencing the issue.
