### ISSUE TITLE
Discard focused tabs on other workspaces

### ISSUE THREAD

**Issue by mjsir911** [rNeomy/auto-tab-discard#114]
Hi,

I am using i3, a linux tiling manager, and have a lot of firefox windows open but on different workspaces or hidden in tab layouts.

It would be nice to have these suspend as well, and unsuspend on focus. 

In the settings, there is an option to "Discard a tab if it is hidden", but that doesn't seem to work.

related: #105

**Comment by rNeomy** [comment]
Unfortunately, as far as I know, it is not doable. See #105 for more info.
