### ISSUE TITLE
No (or very slow?) automatic tab discarding since 0.3.3

### ISSUE THREAD

**Issue by gadfsgagfaq435** [rNeomy/auto-tab-discard#117]
hi

ever since the recent update landed (0.3.3) auto tab discard hasnt been automatically discarding tabs for me anymore (or maybe much slower than my 60s setting not entirely sure)
browser: brave release channel
settings:  [auto-tab-discard-preferences.txt](https://github.com/rNeomy/auto-tab-discard/files/3907266/auto-tab-discard-preferences.txt)
(had to change filetype to txt because github doesnt like json)

before 0.3.3 it worked fine
manual tab discarding (via "discard all other tabs") works fine
it seems to generally ignore all settings-changes i make for example it also changes the icons of tabs even though i have disabled that too

i have already tried factory reset in settings and reinstalling extension

thanks for the great addon :)

**Comment by FunkyFlapjacks** [comment]
Same thing happening here. The discarding is completely broken. Even if you set the the time to 1 second and refresh to also 1 second it doesn't do anything.
Using Chromium Version 80.0.3977.0 (Official Build) (64-bit)

**Comment by rNeomy** [comment]
If you want the old fast behavior, you need to alter one more setting. Set "Minimum delay between sequential discarding checks (in seconds)" to 1 second. Note that as of 0.3.3, the extension waits for this period to over if a new discarding request is received. So say if you have 5 tabs opened and each tab requests discarding within the one-second window, the actual discarding occurs after one second of the last discarding request. Settings the pref to one should give you the old behavior.

btw, you have disabled the favicon painting. Make sure to enable "Change favicon of discarded tabs (if possible)" if you prefer the visual change.

**Comment by gadfsgagfaq435** [comment]
@rNeomy ty for the reply. 
yes i have disabled the change favicon option but it still greys out the favicons and sets a grey dot.
the minimum delay between sequential discarding checks every 30 secs would be perfectly fine.
but if i set discard after 60 secs that means it would have to discard in total after 90 secs or sooner.
but it doesnt. it either takes so much longer that i dont notice it or it doesnt auto discard at all.

ty

**Comment by FunkyFlapjacks** [comment]
>So say if you have 5 tabs opened and each tab requests discarding within the one-second window, the actual discarding occurs after one second of the last discarding request. 

Is there a reason for that? What if, someone has 100 tabs open each requesting discard every 20 seconds with default delay set to 30 seconds, then the actual discarding would start happening only after half an hour or so. Why not discard them immediately to free memory, like before.
And btw that setting still doesn't work as intended (but I see that you've made a commit already so maybe you've fixed it).

**Comment by rNeomy** [comment]
@FunkyFlapjacks this behavior is changed on 0.3.4 release

**Comment by gadfsgagfaq435** [comment]
in 0.3.4 behaviour has changed for me but it still doesnt seem to work
it works initially so if discard timer to 10 and frequency to 10 it discards everything rather quickly
but after a while once i have opened and closed a few tabs auto discarding stops doing anything again alltoghether

thanks

**Comment by FunkyFlapjacks** [comment]
Same here. The discarding of tabs is completely random. I opened ~15 tabs quite some time ago (probably around 20 minutes) and just now 10 of them got discarded immediatelly. Sometimes it doesn't discard, no matter how long you wait. But it definitely does not work as intended.

**Comment by rNeomy** [comment]
I am working on a new fix.

> but after a while once i have opened and closed a few tabs auto discarding stops doing anything again alltoghether

Is this on FF? @gadfsgagfaq435 

> i cant quite figure out what exactly triggers the complete stop of auto discarding sry

I think the timeout is not being triggered somehow so the extension thinks there is an ongoing process.

> "Inactive interval to determine if the computer is in idle state or not" about?

There is a new setting to perform discarding only when the computer is idle. This setting determines the needed period.

> Btw, is there a way to download an older version?

What is your browser @FunkyFlapjacks 

Can somebody give the latest commit on GitHub a try?

**Comment by dobata** [comment]
the latest patch seems to have fixed it 😌

**Comment by rNeomy** [comment]
Thanks @dobata. There is a new commit. Please use the latest for a while to make sure everything works as expected.

**Comment by gadfsgagfaq435** [comment]
@rNeomy brave release channel (chromium)
thanks. so on its own the inactive period setting has no effect only in conjunction with the "do not if not idle" setting. i thought maybe that was the problem but seems you have already figured it out :)
sry have never compiled software myself nor do i know how to. so cant test that commit.

**Comment by FunkyFlapjacks** [comment]
@rNeomy I'm using Chromium 80.0.3982.0 (Official Build) (64-bit), however the latest commit seems to have fixed it! I've only tried it for around 15 minutes so far but it seems like it's working as intended, no issues so far. Thanks for the quick fix! :)

**Comment by dobata** [comment]
had to switch back to 2.5y old The Great Discarder

**Comment by rNeomy** [comment]
Please open a new bug if you are still experiencing the issue.
