### ISSUE TITLE
Preferences are empty

### ISSUE THREAD

**Issue by Henrietta1989** [rNeomy/auto-tab-discard#118]
I have Waterfox 2019.12 and latest Auto Tab Discard.

ATD preferences used to work but now if i go to preferences, all boxes are empty and all radio buttons and checkboxes are empty.

I have tired to disable>enable and clicked factory reset twice.

If i set preferences again and click save options and it says options saved.

If i then just refresh about:addons page and open preferences again, all preferences are gone.

Toolbar button works.

**Comment by Henrietta1989** [comment]
I just removed extension and relaunched browser and then reinstalled it but same problem exists.

**Comment by lucknaumann** [comment]
I have this same issue with Waterfox Classic, based off of FF ESR 56. Windows 10 v1809. 
Actually, this add-on hasn't worked for a while. Even though it appears like the tabs are discarded because the icon changes, they aren't.

**Comment by rNeomy** [comment]
There is nothing I can do. The browser is probabaly not compatible with on of the APIs
