### ISSUE TITLE
View Discarded Tab without refreshing the page

### ISSUE THREAD

**Issue by smorked** [rNeomy/auto-tab-discard#120]
Using other tab suspenders for chrome, I've found it really valuable to have the ability to view the page title of the suspended page before refreshing it.  This allows me to view what the page is before making the decision to bring it back.

**Comment by allanlaal** [comment]
in Firefox 72 Auto Tab Discard keeps tab titles as is

does your experience differ or are we talking about different things?

**Comment by smorked** [comment]
When I visit a discarded page, the page auto-refreshes.

**Comment by rNeomy** [comment]
There is nothing we can do. This is how the native discarding works.
