### ISSUE TITLE
How to make tabs discarded not greyed out?

### ISSUE THREAD

**Issue by nicknicola** [rNeomy/auto-tab-discard#121]
The normal behavior of the extension turns the icon of a tab being discarded grey, upon discarding. There is a possibility to not do that? I barely recognize the icons of the tabs discarded when I have a black theme on Firefox. I don't care about not seeing the difference between discarded and active tabs

**Comment by trlkly** [comment]
There's an option called "Change favicon of discarded tabs (if possible)" which you can disable. 

However, it doesn't seem to be working for me. If it doesn't work for you, either, I would suggest renaming your bug to something like "Disabling Favicon doesn't work."

**Comment by nicknicola** [comment]
Disabling "Change favicon of discarded tabs (if possible)" works!
Thanks for the help. Sorry to hear that it does not work for you, seems like a bug. 

Anyway, it would be awesome if the favicon could have options to change the intensity of grey or more options for black themes. With a black theme on Firefox its almost impossible for users to recognize the original icon.

**Comment by trlkly** [comment]
Does this option still work for you? Because I find that it only works until I restart Chrome.

**Comment by rNeomy** [comment]
Will get fixed by the next release.
