### ISSUE TITLE
Discard wrong tab on toolbar left click

### ISSUE THREAD

**Issue by ddska** [rNeomy/auto-tab-discard#122]
When I'm using add-on popup menu (from add-on toolbar button or tab context menu), everything works fine.
But if I'm setting Toolbar left_click action to "Discard tab" and pressing left click on the add-on toolbar button, the active tab is not suspended. But the tab which was previously active, gets suspended instead of the current one.
It does not happen all the time, but very often (multiple times a day) and I have not discovered the pattern yet.
I'm using Firefox 71.0 on Ubuntu.
Add-on version is 0.3.5.2.

**Comment by rNeomy** [comment]
I am not able to reproduce this anymore. Please reopen if you can
