### ISSUE TITLE
[Feature request] Except hostname from being discarded for the current session

### ISSUE THREAD

**Issue by SEE-ICT** [rNeomy/auto-tab-discard#124]
An example of where this could be useful would be a site on which you are doing frequent lookups that direct you to different pages, e.g., a dictionary on a site you are using to learn a language. Excepting a particular page won't stop the tab from being unloaded if you look up a different word. On the other hand, you may not always want tabs for that site to remain loaded. E.g., if you are later just exploring parts of the site other than the dictionary.

**Comment by rNeomy** [comment]
We are going to have a new button in the popup UI for session-only whitelisting.
