### ISSUE TITLE
[Feature Request] Option to undiscard pinned tabs on startup

### ISSUE THREAD

**Issue by trlkly** [rNeomy/auto-tab-discard#125]
Pinned tabs in Chrome are tabs that launch with every startup. These are convenient for tabs you will always need. Auto Tab Discards helpfully provides an option to keep them from discarding, so they will always be in memory, ready to use. However, one has to click on all manually every time they (re)start Chrome, as Chrome otherwise loads inactive pinned tabs in a discarded state. 

I would thus like to request an option to "undiscard" pinned tabs on startup (perhapss with a configurable time gap between each tab)

**Comment by rNeomy** [comment]
a new option is added for this.
