### ISSUE TITLE
[Feature Request]: Discard tabs that use a lot of CPU

### ISSUE THREAD

**Issue by John-Gee** [rNeomy/auto-tab-discard#127]
Hello,

At times I have tabs that use 100% of a core for no good reason, it would be nice to automatically discard them like we can when they use too much memory.

An enhancement to this, though not sure if possible, would be to switch the active tab in a Window in case the current active one is the offender. Often I have complete windows I don't look at for days and so I don't really care which tab is active or inactive, but the active one is a resource hogger unlike some of the others and I'd rather not have to investigate that one window at a time.

Thank you!

**Comment by allanlaal** [comment]
I see you too are a fan of Google Keep, Google Calendar and Youtube :D

**Comment by John-Gee** [comment]
Youtube yes, the others no, but gmail, and a bunch of badly coded websites can be pretty evil too :)

**Comment by rNeomy** [comment]
Closing in favor of https://github.com/rNeomy/auto-tab-discard/issues/126

**Comment by allanlaal** [comment]
@rNeomy I think automatic suspend based on CPU is different from #126 (which is a manual action)

I suggest keeping this open until Firefox/Chromium implements an API for CPU/Energy Impact

**Comment by rNeomy** [comment]
Just a note that on the 0.4.2 release we have a new plug-in to immediately discard provided hostnames when they are not active.

**Comment by John-Gee** [comment]
Yeah I guess that's a step forward, I can see which tab uses a lot of CPU and add its hostname to the list. What do you mean by active in this case? Only active if in the same window or in other window too?

**Comment by rNeomy** [comment]
> What do you mean by active in this case

When a tab is not the active one on its own window. ATD cannot discard active tabs.

**Comment by John-Gee** [comment]
Can't ATD discard the active tab and move to another one? It seems to work fine when I click on "Discard Tab". In this case I think it'd be good to have the blacklist have priority to being discarded over the rest (ie discard the bad current tab, move to another tab that was discarded before but it's not blacklisted and get undiscard it).

**Comment by kocjs** [comment]
I use about:performance to find out witch tabs are causing high CPU usage. Might be of help here.

**Comment by John-Gee** [comment]
The task manager can also show that, but it's a manual process, so only useful when I know/remember to do that.
