### ISSUE TITLE
Favicons

### ISSUE THREAD

**Issue by rayman89** [rNeomy/auto-tab-discard#13]
I noticed that discarding tabs most of the time makes it loose it's favicon. Is that expected behavior? Could that be fixed? Thank you.

**Comment by rNeomy** [comment]
This is an API implementation bug. Basically, when a tab is discarded, there is no document attached to it hence there is no way to fix the icon issue. I'm sure the discard API will be improved over the time.

**Comment by ssokolow** [comment]
Do you know if a bug for this has been filed on Firefox yet?
