### ISSUE TITLE
ADD button action: open new tab with list of windows

### ISSUE THREAD

**Issue by allanlaal** [rNeomy/auto-tab-discard#130]
## use case

I have hundreds of tabs open in tens of windows on tens of workspaces
since #105 is impossible, I open a blank New tab in a window I wanna have sit in its workspace until (days/weeks later) I find time to continue that task/surfing
this leaves me with a workspace of say 10 windows in the toolbar with all showing "Mozilla Firefox" (the title of about:blank) as the window title, which says nothing about what is open where

## solution

add button action (so it can be selected either from the list of actions and assigned as the default button action aswell) that opens up a new (about: ?) page with a list of currently opened tab titles in this window. that pages title would default to the first tabs title

## optional features
 
 • suspended at timestamp in front of tab title
 • ability to set custom page title (that would be lost when this special page is closed)
      note that plugins like Crappy firetitle and others do not prefix/suffix about: pages titles, so they are useless to fix the default title issues

**Comment by rNeomy** [comment]
Chrome users have chrome://discards/. I assume FF will eventually implement something similar. Meanwhile having a simple stat page is a good idea.

**Comment by grahamperrin** [comment]
Spun off from https://github.com/rNeomy/auto-tab-discard/issues/109#issuecomment-740415737

Food for thought, the _vertical_ view within Tab Manager Plus for Firefox: 

![image](https://user-images.githubusercontent.com/192271/101453235-f1035500-3926-11eb-9a9b-36be0d166b8d.png)

(I normally prefer _block_ view, in a new tab. For the screenshot above I chose to switch view and pop the tab into a separate window on an adjacent display.)

**Comment by allanlaal** [comment]
I like it!

for me setting a custom title is enough, since I get the tab list by a persistent Firefox's built in List All tabs button and I now use Firefox's integrated search from the URL bar to switch to an existing tab by search

**Comment by rNeomy** [comment]
ATD has a new plug-in to show a blank page when "Discard All Other Tabs" or "Discard Tabs in Other Windows" are fired. This blank page is not going to list tabs in the window. It is just a simple blank page for now.
