### ISSUE TITLE
Firefox policies with policies.json with latest version

### ISSUE THREAD

**Issue by DARMAYAN** [rNeomy/auto-tab-discard#131]
Hi ! 
Under Firefox, I'm trying to use the managed storage with the policies.json under Windows. But the paramaters send are not applyed. Here is my configuration (as Mike Kaply said): 

	"3rdparty": {
       "Extensions": {
         "{c2c003ee-bd69-42a2-b0e9-6f34222cb046}": {
           "number": 1,
		   "period": 30,
		   "faqs": false,
		   "whitelist" : "re:silpc.net,re:gesform.fr"
			}
		}
	}

I don't know if there is a problem ...

THX

**Comment by rNeomy** [comment]
I'll test and let you know.

**Comment by DARMAYAN** [comment]
Hi ! Mike Kaply told me that the correct syntax was: 

"whitelist" : ["re:silpc.net","re:gesform.fr"]

And now it works ! Thx
