### ISSUE TITLE
Disabled "Change Favicon in discarded tabs" option ignored

### ISSUE THREAD

**Issue by trlkly** [rNeomy/auto-tab-discard#132]
Even with a complete reinstall and reset of all settings, I can't get ATD to consistently not change the favicons of tabs. I can sometimes get it to start working if I toggle the setting on, open every single discarded tab, make sure none of them have faded icons, turn the option back off, and then discard all other tabs. But, after I restart Chrome, the problem pops up again.

If it matters, I'm using Chrome 79 on Windows 7 SP1, and I use the "Continue where you left off" option upon startup. This problem has been occurring with previous versions. 

Steps to Reproduce:
1. Turn off changing the tab icon.
2. Restart Chrome (e.g. using chrome://restart
3. Open lots of tabs. (optionally before step 2.
4. Wait for them to automatically discard. 

Expected results: discarded tabs do not change icon

Actual results: discarded tabs have faded icon with yellow dot.

Additional information: It's harder to distinguish tabs when the icon gets faded out. Hence why I have always disabled this feature.

**Comment by Mrfiregem** [comment]
This happens to me as well in Edge `83.0.478.45` with the extension version `0.3.5.3`.


It works fine until the browser is restarted, but reverts to the default behavior, even though the setting menu (which is too small in Edge, but that's another issue) still shows it checked.

**Comment by rNeomy** [comment]
I am pretty sure I found the issue. Please wait for the next release and reopen if not.

**Comment by g-i-o-r-g-i-o** [comment]
right now the opposite is happening on firefox on ubuntu: the icon is changed even if the behaviour is disabled

firefox 130

addon version
Version
0.6.7
Last Updated
November 16, 2024
