### ISSUE TITLE
What's the reason for requiring the ``Access your data for all websites`` permission?

### ISSUE THREAD

**Issue by barseghyanartur** [rNeomy/auto-tab-discard#135]
What's the reason for requiring the ``Access your data for all websites`` permission?

**Comment by Luckz** [comment]
Chrome exposes only limited data about tabs to extensions that don't have the permission. You can test this yourself by running tab-related commands from the background page of any extension that has it vs any that does not, you can't see or do that much without this permissions.

https://developer.chrome.com/extensions/tabs

**Comment by barseghyanartur** [comment]
@Luckz:

```The majority of the chrome.tabs API can be used without declaring any permission. However, the "tabs" permission is required in order to populate the url, pendingUrl, title, and favIconUrl properties of Tab.```

Thanks. I assume the same goes for Firefox. Thus, actually in order to obtain the URL of the tab (```"tabs" permission is required in order to populate the url```), we need this tabs permission?

**Comment by barseghyanartur** [comment]
Still, what's unclear to me, as far as I can see, we have 2 separate permissions here:

- [access-browser-tabs](https://support.mozilla.org/en-US/kb/permission-request-messages-firefox-extensions#w_access-browser-tabs)
- [access-your-data-for-all-websites](https://support.mozilla.org/en-US/kb/permission-request-messages-firefox-extensions#w_access-your-data-for-all-websites)

As far as I understand this extension, from what it does, it simply suspends the tab after X time of inactivity. Thus, the question remains open: Why is ``Access your data for all websites`` permission needed (if tabs permission is sufficient)?

**Comment by fermulator** [comment]
This is a reasonable consideration/ask; if we can make the extension work without `access-your-data-for-all-websites` that would be preferred.

**Comment by rNeomy** [comment]
A simple extension that just does discarding works without the "chrome.tabs" permission. But if you need to have access to the hostnames, this permission is needed.
