### ISSUE TITLE
Tab that a Picture-in-Picture video was launched from was discarded

### ISSUE THREAD

**Issue by mxmilkiib** [rNeomy/auto-tab-discard#136]
Which thus closed the Picture-in-Picture video. The disable discarding during media playing checkbox is ticked.

**Comment by kiwi5** [comment]
I can confirm that this has happened to me a while ago as well - when using Twitch on Windows 7, in this case.  However, I tested it now on Firefox 75, Windows 10, Auto Tab Discard 0.3.5.2, and it does not occur to on my system.

I think it may be closed now.

**Comment by vhfmag** [comment]
I can confirm this is still happening on Firefox 77, Windows 10, Auto Tab Discard 0.3.5.2. I'm without my notebook right now, but it still happened two weeks ago in it.

**Comment by rNeomy** [comment]
I am adding a new method to detect media playing. Please reopen if the next release also has the reported issue.

**Comment by ssokolow** [comment]
I'm not sure whether the patch for this has made it into the version I'm running (0.3.6), but I have to manually choose "Keep This Tab For This Session" so that a paused Picture-in-Picture window doesn't risk getting discarded.

Is this fix in 0.3.6 and, if so, should I open a new feature request for "Don't discard tabs with Picture-in-Picture active, even if playback is paused"?

**Comment by rNeomy** [comment]
@ssokolow  I added a new fix to consider a media as it is playing when it is in the PIP mode even in the paused state. However, Firefox does not support reporting the state of PIP right now, so it only works on Chrome until `document.pictureInPictureElement` is supported by FF.

**Comment by anohren** [comment]
> I have to manually choose "Keep This Tab For This Session" so that a paused Picture-in-Picture window doesn't risk getting discarded

> it only works on Chrome until `document.pictureInPictureElement` is supported by FF

Nice work. I was just about to report the same issue in 0.3.6. 

No idea how to determine FFs interest in implementing that property though. They at least don't list it on their document API page.
