### ISSUE TITLE
Is there a way to disable automatically reloading a discarded tab when refocusing

### ISSUE THREAD

**Issue by chrisbenincasa** [rNeomy/auto-tab-discard#137]
Hi there - thank you for the great extension. I recently switched from Chrome to Firefox and I began using this plugin in place of "The Great Suspender". I'm wondering if there is a way to configure this plugin to not automatically reload a discarded tab when the tab is refocused. Frequently, I'll have many tabs open and it's unclear which discarded tab is the one I actually want, so I could erroneously reload many tabs just to find the one I'm looking for. In The Great Suspender, these tabs would be frozen and show a static page that described the tab that was suspended -- does that feature exist here?

**Comment by keithx2** [comment]
No, that feature doesn't exist.  While some may want it, they'd probably be in the minority.
Have you tried the Tab Suspender extension?  That may be what you want.  
https://addons.mozilla.org/en-US/firefox/addon/ff-tab-suspender/

There are also extensions like Tree Style Tabs that help with viewing the tab titles when there are a lot of tabs open.

**Comment by ViciousPenguins** [comment]
Thanks for pointing me to Tab Suspender.  I liked your add-on, but I switch tabs with the keyboard and was constantly reloading pages that I wanted to remain discarded, so not restoring on tab focus was a must have for me. :)
