### ISSUE TITLE
"not being discarded" hostnames not honoured.

### ISSUE THREAD

**Issue by TomTrottier** [rNeomy/auto-tab-discard#139]
i have "re:duckduckgo,  re:google, re:bridgebase" in my "not being discarded" list - but they are being discarded. This is especially obvious with duckduckgo html version where the URL is always the same.

**Comment by CSP197** [comment]
You'll need the actual hostname to prevent it from getting discarded

For example:
```
www.google.com, www.duckduckgo.com, www.bridgebase.com
```

**Comment by alimhanif** [comment]
Can I use a wildcard, perhaps `*.google.com`?

**Comment by rNeomy** [comment]
@alimhanif see the footnote. There is a regex support.
