### ISSUE TITLE
White-listing websites creates a runtime error.

### ISSUE THREAD

**Issue by christopherboss** [rNeomy/auto-tab-discard#140]
I'm using Microsoft Edge version 80.0.361.66 and every time I access a tab that's white-listed I get a console log error.

`Unchecked runtime.lastError: The message port closed before a response was received.`

Any fix in the pipeline for this?

**Comment by rNeomy** [comment]
Do you still have this issue? If so, please reopen the bug report. Please share more info and possibly a screenshot of the error. What do you have in the exception list?
