### ISSUE TITLE
[Bug] Switching to discarded tab using URL bar occasionally does nothing

### ISSUE THREAD

**Issue by grinser** [rNeomy/auto-tab-discard#141]
This is what happens for me occasionally when I want to go to a tab that I opened a while ago and has been discarded using the Firefox URL bar:

1. Open empty new tab.
2. Type parts of the title or URL of the tab I want to go to into the Firefox URL bar
3. Firefox URL bar auto complete suggests "Switch to tab"
4. After pressing enter, nothing happens (except the focus is gone from the URL bar)

I couldn't pinpoint what's the exact reason behind it not working vs. working with a discarded tab, but it feels like happening mainly with ones that are discarded for a longer time.

**Comment by JamesFerguson** [comment]
Ohhh, that's why I see Switch to tab not working. Thanks, I wouldn't have put that togther. So, yeah, I've seen this bug too.

**Comment by grinser** [comment]
Out of curiosity – does that also happen in other browsers?
Any lead if that's an extension or browser issue?

**Comment by braham-snyder** [comment]
I run into this bug all the time, but I do keep an absurd number of tabs open/discarded (about 500 at the moment)

**Comment by rNeomy** [comment]
Most likely this get fixed by the next release. Please reopen if not
