### ISSUE TITLE
Ability to close old tabs instead of suspending them

### ISSUE THREAD

**Issue by zenwalker** [rNeomy/auto-tab-discard#142]
There’s an amazing extension for chrome which is able to close the least used tab when it reaches the limit of opened tabs called xTab. And there’s no alternative in Firefox world unfortunately and I thought maybe the author of this extension might be interested in implementing a similar policy toward tabs (optionally). I often find myself closing discarded tabs without thinking when there’re too many of them.

**Comment by cehteh** [comment]
I'd second that. Something like have a secondary timer which closes tabs after they are suspended. Could/should be off or a reasonably high value by default (2 days or more). Actually automatically removing tab-clutter was what i wanted in the first place...

**Comment by rNeomy** [comment]
As of the next release, there is a new checkbox in the popup view which lets the user enable the trashing of discarded tabs.
