### ISSUE TITLE
Sometimes discards the wrong (previous) URL (?)

### ISSUE THREAD

**Issue by ForsakenHarmony** [rNeomy/auto-tab-discard#147]
I'm not sure if this is a bug with Firefox or this extension.

Sometimes when I click on a suspended tab, it unsuspends to the previous page (like pressing the back button prior to suspending) and seems to be missing the latest version, I can't go forward from there

**Comment by ForsakenHarmony** [comment]
Just noticed the previous page seems to be pushed to the top of the history, so if I press back I can get to the page that was supposed to be suspended
(and back twice to get to the same page)

**Comment by JamesFerguson** [comment]
I've seen this too. But I've also seen it, I guess maybe because the previous page was a new tab page (I use momentum), fail to unsuspend anything. It just shows a blank tab and the tab name is "New tab" and my tab is gone.

**Comment by ForsakenHarmony** [comment]
I think that might be a different issue I've also run into

**Comment by terminatorOST** [comment]
It's a bug with Firefox, I've noticed it, when I've updated from version 74.0.1, since I've rolled back it stopped happening.

**Comment by machinemessiah** [comment]
Has anyone who's experiencing this issue had any luck using a previous version of the addon (rather than rolling back Firefox - which is a less desirable solution, well, for myself at least)?

**Comment by kernc** [comment]
Possibly related issue: https://github.com/rNeomy/auto-tab-discard/issues/95.

**Comment by rNeomy** [comment]
Should be fixed by the next release.
