### ISSUE TITLE
Option: Bypass cache on restore

### ISSUE THREAD

**Issue by AtTheGates** [rNeomy/auto-tab-discard#149]
Hello,

first thank you very much for this great extension. I really like it.

I would love to see an option to **Bypass the cache on restore**. Would that be possible, if you get the time?

Thank you very much in advance.

**Comment by rNeomy** [comment]
You need to hard refresh a tab with Shift +Ctrl + R. As of the next release, use the popup menu for that. There will be a "release" button, and Shift + Click on these buttons will do the hard-refreshing.
