### ISSUE TITLE
[Feature Request]: Add a configurable delay before waking a tab

### ISSUE THREAD

**Issue by dcrosta** [rNeomy/auto-tab-discard#150]
I'm in the habit of navigating tabs (in Firefox) with `⌘+⇧+{` and `⌘+⇧+}`; since I started using Auto Tab Discard, I've struggled to break this habit, as flipping past tabs in this way wakes them and defeats the purpose of the add-on.

It'd be great if there was a way to detect that this was going on and not wake tabs, possibly something as simple as a short (configurable) delay before waking, so that as you flip past they don't wake unless you settle on that tab.

**Comment by rNeomy** [comment]
This extension only asks your browser that a particular tab needs to be in the discarded state. Unfortunately, at this moment there is no control over how discarded tabs behave. So as soon as they get focused, the browser reloads them. The only workaround, for now, is to set up custom navigation for this extension and use them to navigate left and right.

**Comment by NewtMa** [comment]
There's this extension called TabSuspender seems working just fine. Couldn't we have that feature?
