### ISSUE TITLE
Preserve the state of pinned tabs when restoring a session

### ISSUE THREAD

**Issue by TobiaszCudnik** [rNeomy/auto-tab-discard#151]
The state of pinned tabs when restoring a session should remain the same as before the browser was closed.

At least please introduce a config option. I tend to have many of them combined with TST, out of which only some aren't "discarded", which causes unnecessary overhead. Thanks.

**Comment by rNeomy** [comment]
Restoring tabs after a restart is not being handled by this extension. I guess your browser decides whether the pinned tabs should be discarded or not.

**Comment by TobiaszCudnik** [comment]
Can you force-discard them after a restart? As a workaround of course.

**Comment by rNeomy** [comment]
We are going to have these four new options:

![Screen Shot 2020-06-24 at 9 58 37 AM](https://user-images.githubusercontent.com/14104614/85519137-8e283680-b5f0-11ea-89d5-10a72e94b9e1.png)

**Comment by TobiaszCudnik** [comment]
This unfortunately doesnt work.

Having "Discard all pinned tabs..." checked, I still get them reloaded 1 by 1 on a browser startup. Ideally it'd memorize which of the pinned tabs were discarded and force-discard them on startup (not all of them). 

I have a lot of pinned tabs and it takes them 30-60secs to reload all, which may be the reason.

The current workaround is to hit "Work Offline" as soon as the browser starts.

**Comment by TobiaszCudnik** [comment]
### Solution

Set **browser.sessionstore.restore_pinned_tabs_on_demand** to **true** in **about:config**. [Source issue](https://bugzilla.mozilla.org/show_bug.cgi?id=708585).
