### ISSUE TITLE
Add "Discard Tab" To Right Click Menu On Tabs - Edge Browser

### ISSUE THREAD

**Issue by sayjay09** [rNeomy/auto-tab-discard#152]
Firefox has this feature and I would love to see it on Edge. 

The reason for this is when you focus the tab you want to discard, discard it, then it could open another discarded tab when that is complete but just having the option on the right-click menu would avoid this.

Great work on the extension though, I loyally install it on every browser :)

**Comment by rNeomy** [comment]
This extension requests to add the same menu for all browsers. At this moment, no Chromium browser supports appending extension's context menu items for the tab area. So as soon as it is supported, you will get it without any updates required.
