### ISSUE TITLE
Auto Tab Discard Firefox Addon

### ISSUE THREAD

**Issue by Clemens-Ratte-Polle** [rNeomy/auto-tab-discard#154]
Hi.
- How does the discarded page look like? Is there a screenshot?
- Does it discard with a "native" Firefox technology? 
- When restarting FF will all discarded pages be recovered discarded?
- When uninstalling "Auto Tab Discard" will all discarded pages stay discarded and lost??

thx

**Comment by rNeomy** [comment]
> Does it discard with a "native" Firefox technology?

Yes

> When restarting FF will all discarded pages be recovered discarded?

Your browser handles discarding so yes.

> When uninstalling "Auto Tab Discard" will all discarded pages stay discarded and lost??

They stay intact
