### ISSUE TITLE
Potential bug: text entry not properly recognized in certain pages that don't use 'form' fields

### ISSUE THREAD

**Issue by infinitebuffalo** [rNeomy/auto-tab-discard#155]
My primary example of this is on Twitter, where new-post and reply boxes don't use proper HTML form fields and thus aren't recognized as having active form entries.  I've lost several half-written posts to the auto discard mechanism.  (It being twitter, the world is probably not worse off for the loss, but still...)

A couple thoughts on how this might be possible to mitigate: 

- The never-discard list currently accepts hostnames---but I don't necessarily want _all_ twitter tabs to not discard, just ones with active replies or new posts.  As far as I can tell, these will all display in the address bar as `(mobile.)?twitter.com/compose/tweet`---is it possible to whitelist a single address, rather than an entire domain?

- I'm not, frankly, _entirely_ clear on the details, but it appears Twitter, rather than using form elements, is using a stack of nested `<div>`s, one of which has `role="textbox"`---I don't know how widely this is done, but could that possibly be added to how the extension checks for active form input?

Thanks,

**Comment by rNeomy** [comment]
Should have already been fixed. Please reopen if not.
