### ISSUE TITLE
Discard tab at startup

### ISSUE THREAD

**Issue by JibsouX** [rNeomy/auto-tab-discard#156]
It will be a good thing to add a "discard tabs at browser" startup like the extension "Sloth".

**Comment by sharadkhanna** [comment]
Bumping as this is a highly desirable feature as this would allow users to load up a group of tabs or bookmarks quickly and without causing high memory and cpu consumption.

**Comment by rNeomy** [comment]
We are going to have two new options to discard pinned and unpinned tabs on a browser restart.

**Comment by rNeomy** [comment]
> to load up a group of tabs or bookmarks quickly and without causing high memory and cpu consumption.

This extension has the "Open Link in New Discarded Tab" context menu item for links which is what you are looking for, however, this menu is not available on the bookmark tree (Chrome does not support it, and FF needs "bookmarks" permission for that which is just too much).
