### ISSUE TITLE
Random discarded tab cannot be clicked and opened.

### ISSUE THREAD

**Issue by drpcken** [rNeomy/auto-tab-discard#157]
Firefox 76.0.1 (64-bit)
Auto Discard Tab 0.3.5.2

I've only been using this addon a few days.  It's been very useful, however I've noticed an issue that happens often, sometimes several times a day.

I'll have a lot of discarded tabs (though I don't think the number of tabs is relevant to the issue).  Then randomly, 1 tab that has been discarded will not respond when I click on it.  I can't close the tab, I can right click to get a menu, but none of the commands work. It's as if the tab is completely unresponsive.  The only way to fix it is to restart firefox ( I use about:profiles page to restart so I can keep my opened tabs).  I made a gif of the issue.

![autodiscardtab](https://user-images.githubusercontent.com/435835/82758654-6d7c7f00-9dad-11ea-80ca-b03121bdf125.gif)

Despite the issue I adore this add-on!

**Comment by rNeomy** [comment]
I think this issue is already fixed on the newer versions of FF. Please reopen if not.
