### ISSUE TITLE
slimmed and streamlined user interface

### ISSUE THREAD

**Issue by naturallymitchell** [rNeomy/auto-tab-discard#160]
this extension works well, but it is slightly bloated and could use some UI/UX love

another extension which is tiny and worth review is
https://github.com/idupree/chrome-tab-unloader https://chrome.google.com/webstore/detail/chrome-tab-unloader/ncifninngopkimemifelcaelaaigceod?hl=en

, but the selection options for multiple tabs is useful

the automatic discarding is not always needed and could possibly be removed, separated, or refactored and integrated with a generic rules engine

**Comment by rNeomy** [comment]
go to the options page and change the left-click action to "Discard Tab". For other options, use the right-click context menu items over the browser action.
