### ISSUE TITLE
Feature request: toolbar icon on left click Keep This Tab for This Session

### ISSUE THREAD

**Issue by Ultima0** [rNeomy/auto-tab-discard#164]
I usually leave this add-on alone to auto-discard inactive tabs. The only time I interact with it is to tell it not to discard a particular tab, which I do by opening the toolbar popup menu and clicking the option "Keep This Tab for This Session". 

I would like an option in the settings menu to enable keeping a tab for the session by left clicking the toolbar icon. Preferably with some visual change to show that the tab will be kept (either on the toolbar icon or as a different colored dot on the favicon).

Thanks!

**Comment by rNeomy** [comment]
We are going to have a new left click selector for "Keep This Tab for This Session".
