### ISSUE TITLE
Tabs are still discard with form entries if inputs are not in `<form>` tag

### ISSUE THREAD

**Issue by michaelmior** [rNeomy/auto-tab-discard#166]
As the title states, if I have a tab with form fields that are not actually wrapped in a `<form>` tag, the tab is still discarded. I believe it's due to the following in `data/inject/all.js`:

```js
document.addEventListener('change', e => e.target.closest('form') && post({
  form: true
}), true);
```

Could `'form'` here just be changed to `'input'`? I guess more generically, what change events should still allow a tab to be discarded? If there aren't any, it seems this check is not needed at all.

**Comment by rNeomy** [comment]
This way there is no way to know when we can resume discarding;

```js
document.addEventListener('submit', () => post({
  form: false
}), true);
```

**Comment by michaelmior** [comment]
I think it would be safer to never resume discarding. Personally I'd rather have a tab not discarded than lose data. Although this could reset on moving to a new URL (which did happen in the particular case I mentioned).

**Comment by rNeomy** [comment]
The next release should fix the issue. Please reopen if not.
