### ISSUE TITLE
trash discarded tabs setting is not clear

### ISSUE THREAD

**Issue by mattarderne** [rNeomy/auto-tab-discard#167]
From the config, it is not clear if the risk of trashing inactive tabs is enabled. This should be a clear OPT_IN on the settings page.

`Also trash discarded tabs if they are inactive for about (in hours) (if enabled from popup`

**Comment by zhurin** [comment]
I agree and came here looking to find what exactly this option does, what it means by "trash", what popup it's referring to, and what happens if the popup is not enable. Lastly, does entering 0 disable this functionality?

**Comment by rNeomy** [comment]
Thanks guys for the feedback. We are going to have `(permanently delete)` appended on both options page and the popup window.

**Comment by ZirconCode** [comment]
Thanks for maintaining! I also had this issue, one small nitpick, I still have no idea what "the browser action's popup window" means and even with @zhurin's guide I cannot find it.

**Comment by zhurin** [comment]
@ZirconCode: Click the Auto Tab Discard button on the browser's toolbar. That opens a menu (unless you changed the behavior of the toolbar button in the addon's options) where you'll find the aforementioned setting is the last menu item.

**Comment by Franzl123** [comment]
sorry for reopening

i've just the idea, that the option in the setting page (where you can set the time) is disabled additionally, if the checkbox in the popup window is disabled. and/or the checkbox of the popup window should be moved to the settings page
