### ISSUE TITLE
"Discard Tab Group" option gone in new versions

### ISSUE THREAD

**Issue by rva2895** [rNeomy/auto-tab-discard#168]
[Firefox 68.10.0esr, Tree Style Tab 3.5.13]

In 0.3.5.2, I can discard an entire tree using the "Discard Tab Group" option.
In newer versions, the option is no longer available.
Is this a bug, or was the option removed on purpose, and if so, for what reason?

**Comment by Sada-Mio** [comment]
I miss this feature!

**Comment by irvinm** [comment]
@rva2895 I took a quick look thru the code and it looks like everything is still there to support this feature.

https://github.com/rNeomy/auto-tab-discard/blob/1666720f5d2f68783b38f6c6bd2edabf6628abd8/_locales/en/messages.json#L207

https://github.com/rNeomy/auto-tab-discard/blob/87abd6cf670765973ea1032d3b19e3060f54645a/menu.js#L30

I was thinking of placing a feature request for this (I am a big TST user) and being able to discard a tree would be very useful.  If this worked before, it might be a bug now.

**Comment by irvinm** [comment]
I spent some more time on this today to see if I could see what was going on.  I started by trying to isolate which versions of TST and ATD work together.

The change that pointed to the breaking point was:
Works: TST 3.6.5 (Current) \ ATD 0.3.5.2
Broken: TST 3.6.5 \ ATD 0.3.6

I then started looking at what changes went into ATD 0.3.6 and actually there were quite a few done on June 23rd and June 24th last year.  Then I loaded a snapshot after each check-in to see when things broke.

I was able to isolate the check-in which breaks compatibility with TST:  https://github.com/rNeomy/auto-tab-discard/commit/01a79b177685ad9c91af69c0614e8cfb0332b0cc

That check-in touches 3 files:  messages.json (won't be the issue), index.html (won't be the issue), and menu.js.

In menu.js, the only change that seems to be related to TST is the moving of this block of code:

          arr.splice(1, 0, {
            id: 'discard-tree',
            title: chrome.i18n.getMessage('menu_discard_tree'),
            contexts,
            documentUrlPatterns: ['*://*/*']
          });

![image](https://user-images.githubusercontent.com/979729/104853368-5f481980-58ce-11eb-9047-77d1a4726b0f.png)

**Comment by irvinm** [comment]
One other data point.  I moved that block of code back in the latest version of ATD (0.3.7) and the menu item now shows up and works.  I also confirmed that the logic check of "if (r === true) {" is not evaluated as true and hence why the menu item is not created in the latest version.

I guess @rNeomy will need to comment on his thoughts for this original change.

**Comment by irvinm** [comment]
I think I know what the problem is and why the behavior changed.  From the TST wiki:

> On TST 3.0.12 and later, the returned promise will be filled with an object with following properties, when TST successfully process the message:
> 
>     grantedPermissions: An array of strings, currently granted permissions.
>     privateWindowAllowed: A boolean, indicating allowed (or not) to be notified messages from private windows.
> 
> On TST 3.0.11 and older, the promise is filled with just a boolean value true.

So, based on the older version of TST, checking for TRUE after trying to initialize with TST makes sense.  However, newer versions of TST return an object and the check for TRUE will never happen.

From the TST wiki as well:

```
  try {
  let result = await browser.runtime.sendMessage(TST_ID, {
    type: 'register-self',
    // The name of your addon (string, optional)
    name: browser.i18n.getMessage('extensionName'),
    // Icons (used for extra context menu items, works on TST 2.4.18 and later)
    icons: browser.runtime.getManifest().icons, // { '16': '/path/to/icon.png', 24: '...', ... }
    // The list of listening message types (array of string)
    listeningTypes: ['tab-mousedown', 'tab-mouseup'],
    // Extra style rules applied in the sidebar (string, optional)
    style: `
      .tab.unread {
        color: red;
      }
    `,
    // Extra permissions to receive tab information via TST's API (works on TST 3.0.12 and later)
    permissions: ['tabs']
  });
  }
  catch(e) {
    // TST is not available
  }
```

**Comment by rNeomy** [comment]
It looks like we don't need to add fake menus anymore. I just removed the integration code. Also, added the "Discard Tab Group" item back.

**Comment by irvinm** [comment]
@rNeomy I see that you checked in version 0.4.0 on Tuesday and it has landed for Chrome, but not Firefox.  I know Mozilla can be slow with the review process, but just wanted to see if you heard anything back from them.  They normally don't take more than a day or two.

**Comment by rNeomy** [comment]
@irvinm 0.4.0 is not yet submitted to AMO. There are still some fixes needed to make it compatible. Will try to submit it by the next week.
