### ISSUE TITLE
Improvement request: Option to discard older tabs when more of X tabs are loaded or when more of X Mbs RAM are consumed

### ISSUE THREAD

**Issue by MalkavianBilbao** [rNeomy/auto-tab-discard#17]
I like much more "Tab Suspender (memory saver)" behaviour. Discarding on time it's great, but it's less useful than discarding depending of tabs loaded or RAM memory consumed.

Thanks for your great work

**Comment by rNeomy** [comment]
okay, the latest dev version has this. Please give it a try and confirm that it works as expected.

Basically, there are two modes of operation:
1. timer-based
2. number-based

Switch to the number-based discarding and check the console for outputs. If you are on FF, use FF >=59
