### ISSUE TITLE
'Keep This Tab for This Session' only stays active until you reload the page

### ISSUE THREAD

**Issue by MoneyAllDay** [rNeomy/auto-tab-discard#173]
There is a problem with 'Keep This Tab for This Session' that only stays active until you reload the page, shouldn't it be stay active until you close/restart Firefox?

It was always like this since i can remember.

Auto Tab Discard 0.3.7
Firefox 80.0 (64-bit)
Windows 10 (64-bit)

**Comment by rNeomy** [comment]
Will get fixed by the next release. Please reopen if not.
