### ISSUE TITLE
[Feature Request] Do not discard tabs which have unsaved data on them

### ISSUE THREAD

**Issue by Mark-Booth** [rNeomy/auto-tab-discard#174]
Normally, if you try to close a tab which has unsaved data (an incomplete facebook post, reply or twitter post etc), your web broswer will pop up a dialogue asking if you want to stay on the page or leave it, preventing you from losing what you've written.

Auto Tab Discard does not respect this, and will happily auto-discard a tab containing unsaved data if you don't access it frequently enough while writing it.

To work arond this, I typically have to manually exclude sites such as facebook and twitter, but occasionally I lose data on sites I haven't explicitly excluded when I firget about this unexpected behaviour.

It would be good if Auto Tab Discard could treat pages with unsaved data teh same as it does with unsubmitted forms.

**Comment by paulidavey** [comment]
The Great Suspender extension on Chrome seems to detect this better - I don;'t know if that's because of a different API.

It also seems faster to restore - maybe it suspends more to disk rather than discarding - but I prefer FF so use that more.

**Comment by rNeomy** [comment]
I added a new method to check if any script already registered an event to block leaving the page. If so, the extension considers the page to have an unsaved form.
