### ISSUE TITLE
[Request] Add easy options to whitelist individual URLs / tabs

### ISSUE THREAD

**Issue by Ultrabenosaurus** [rNeomy/auto-tab-discard#175]
Currently it is very easy to whitelist entire domains, but not individual tabs or specific URLs. It would be nice if whitelisting a specific tab, group of tabs (native ctrl + click grouping), or explicit URL was just as easy as it is for domains. 

I haven't tested it yet but this can probably be done with the existing regex functionality, but I would wager that regex is not something most users of this extension know how to use. It is also not very quick to implement whenever someone wants to add a new exception, even if they do know regex.

**Comment by rNeomy** [comment]
Permanently whitelisting tabs doesn't make sense since browsers change tab ids each time the browser restarts. However, I added a simpler way to generate the regexp rule by pressing the shift key for the "Always" button of "Keep Tabs for This Site".

**Comment by CTimmerman** [comment]
Googlers looking for a ATB exceptions list syntax example:
`re:^https://mail\.google\.com/mail/u/2/\#inbox$, foo.bar.com`
