### ISSUE TITLE
Reddit tabs are prevented from being discarded by an unsaved form, yet no form has been filled (by the user)

### ISSUE THREAD

**Issue by DDzwiedziu** [rNeomy/auto-tab-discard#176]
Version 0.3.7 
Firefox 81.0

This happens at least for the main page and post pages.

I've tried resetting to factory settings.

Edit: also please direct me if more information is needed, as I'm so-so with the Firefox console and JS.

**Comment by rNeomy** [comment]
Should be fixed by the next release. Please reopen if not.
