### ISSUE TITLE
can you make it force discard current tab on demand?

### ISSUE THREAD

**Issue by mailinglists35** [rNeomy/auto-tab-discard#18]
![image](https://user-images.githubusercontent.com/2054302/36333585-4d267ea4-1380-11e8-88db-b1c46b9bf400.png)

is this a firefox limitation or is an extension limitation?
if it's a firefox, what is the firefox bugzilla number?

**Comment by rNeomy** [comment]
This is not a bug. When a tab is active, it needs its document to show it to the user. When a tab is discarded, there is no document attached to the tab. So you need to first hide the tab and then ask for discarding. Note that this extension actually discards the tab. Other extensions replace the document with an internal resource.

**Comment by mailinglists35** [comment]
so it's a limitation of the browser, right? because on chrome i can go to task manager and kill the active tab (and i can reopen it thereafter)

**Comment by Ryman** [comment]
Would it be possible to navigate to another tab when the user requests to discard the active tab, and then discard it? (similar to how unloadtabs used to work)

**Comment by rNeomy** [comment]
I can switch to another tab, but what if the other tab is already discarded?

**Comment by Ryman** [comment]
From memory the unloadtabs behavior was that it would find the next non-discarded tab but I can't remember how it worked if all other tabs were discarded, but either going to the next tab and reloading it or opening about:newtab seems equally fine to me.

**Comment by allanlaal** [comment]
seems that #18 is not fixed. currently active focused tabs are not discarded

I would vote for just opening a new about:blank and focusing on it, if its not possible to discard focused tabs -- thats what I do manually with 30 windows and 235 tabs open every day anyway :)
