### ISSUE TITLE
feature request: discard active tab in every open window except the one I'm using now

### ISSUE THREAD

**Issue by tinkerer42** [rNeomy/auto-tab-discard#182]
Hi,

The way I use firefox is to have a bunch of windows open (typically 10 or more) with anywhere from 1 to 30 tabs in each window. I think auto-tab-discard doesn't help me as much as it could, because it doesn't discard the active tab in *every* firefox window, leaving me with 10 or more active tabs that were not discarded.

would you consider adding discarding for the active tab with the usual timeout in all windows except the one I am actually currently using?

thanks!
Guy.

**Comment by rNeomy** [comment]
There will be a new option on the next release under the plugin section that can be used to prevent tabs in the active window from being discarded.

**Comment by tinkerer42** [comment]
actually what I meant was the opposite behavior... if I have 5 windows with 10 tabs each, currently I get 45 discarded tabs and 5 active tabs. what I want is to have 49 discarded and one active tab (the one I'm actively using right now).

**Comment by rNeomy** [comment]
Discarding the active tabs is not doable. So you are going to have at least one active tab per window. Unless you open a blank page for each window and set the "when the number of inactive tabs exceeds" option to zero which is supported on 0.4.1

**Comment by tinkerer42** [comment]
I understand. thank you for your response.
