### ISSUE TITLE
Auto Tab Discard is disturbing me while developing an extension

### ISSUE THREAD

**Issue by h-h-h-h** [rNeomy/auto-tab-discard#184]
I'm developing an extension in Firefox Developer Edition v84, have loaded it with `about:debugging`, regularly reloading it and am inspecting the dev console there. Auto Tab Discard is constantly, repeatedly causing the following error message that has nothing to do with my extension:

> Unchecked lastError value: Error: isPlaying is not defined
> &#xa0;&#xa0;&#xa0;&#xa0;<anonym> moz-extension://[redacted]/background.js:365

**Comment by ElhemEnohpi** [comment]
I'm also seeing many errors in the browser console in Firefox, the same "isPlaying is not defined".

**Comment by rNeomy** [comment]
Can you please share a page that causing these errors?

**Comment by rNeomy** [comment]
Should be fixed by the next release. If not please provide an example page that causes this issue.
