### ISSUE TITLE
[Feature request] Would be cool to have an option to always keep a tab with a specific page address, not just the whole site.

### ISSUE THREAD

**Issue by azat11** [rNeomy/auto-tab-discard#185]
Very often I REALLY want to keep a specific address tab always open, but all other tabs from that site discarder as usual. That would significantly improve the usability for me.

**Comment by rNeomy** [comment]
Go to the options page and add a regexp rule to just match one URL. 

As of the next release, you can shift + click on the "Always" button inside the popup view so that the extension generates the rule for you.
