### ISSUE TITLE
[Feature Request] Auto un-discard 1 tab to the left

### ISSUE THREAD

**Issue by contribucious** [rNeomy/auto-tab-discard#186]
Hello,

First of all, thank you for this extension, which is very useful to me.
And thanks for adding [this feature](https://github.com/rNeomy/auto-tab-discard/issues/159) too!

Would it be possible however to add the same principle, but for 1 tab towards the _left_?
:arrow_right: i.e. `release-previous-tab` _— possibly using a drop-down list in the settings page for the right or left choice._

Indeed, like @umlautfever, I also often open several links from an "index" page but tend to read the last one opened first personally. And, at least in my Firefox configuration, when I close the most recently opened tab (`ctrl+w`), it will always be the second to last opened (i.e. the penultimate one, so the one to its left) which will be open then, but unfortunately it will take a long time to load each time because it will have often been discarded (especially in the case of long articles to read or if I did something else during this time).

Thanks in advance! :thumbsup:

**Comment by contribucious** [comment]
**[BONUS]** On this subject, at the time, an old Firefox extension also allowed to define the number of tabs to un-discard in this case. That could be nice too.

:arrow_right_hook: (a value of "2" could be particularly useful for people who often open a set of tabs with very little reading, such as very short news briefs where the tab is closed quickly hence; thus making it possible to never have to potentially see a page that un-discarded itself in front of our eyes, therefore improving the user's surfing experience. :v:)

**Comment by rNeomy** [comment]
We are going to have a new plug-in to un-discard 1 tab to the left

**Comment by contribucious** [comment]
Yay! Thank you @rNeomy! :thumbsup:
