### ISSUE TITLE
Trash Discarded Tabs Option Not Working

### ISSUE THREAD

**Issue by dabat** [rNeomy/auto-tab-discard#189]
It appears that the trash tabs option is not working, or perhaps I have not configured it correctly?

I enabled the option on the extension control panel, and the hours is set to 24 in the options page, but no discarded pages are being deleted/trashed.

How is this feature activated?
Thanks!

I'm running firefox 83 on windows 10
![image](https://user-images.githubusercontent.com/37282138/102387975-b50b6800-3f96-11eb-893b-8e97232a2353.png)

**Comment by Mickael-Martin** [comment]
Same issue for me.

**Comment by kgc35** [comment]
Any updates? I set the tabs to get trashed after 72 hrs.
However, it is more than a week, and now I have close to 200 tabs open! 
This should not be a problem if this feature was working.

**Comment by rNeomy** [comment]
I am investigating. Does anybody have this problem on Chrome?

**Comment by rNeomy** [comment]
@kgc35 have you restarted the browser during these hrs? Note that the timer resets itself if the browser restarts.

**Comment by Barleyman** [comment]
@rNeomy Could we have the timer NOT reset itself between restarts? 

My wife uses tabs as bookmarks and there are heaping piles of them. Setting the timeout to too short would definitely draw flak but I recon killing tabs not opened for 7 or maybe 14 days should be safe. At the moment session manager says there are 1573 tabs open in Firefox. That volume just simply cannot be managed manually and blanket removal causes marital crisis. 

So.. Could we save the state, pretty please?

**Comment by rNeomy** [comment]
As of the next release, we will have a new trash plug-in. This plug-in works based on URLs, not IDs and there is no reset between restarts. Hopefully, it fixes all the issues reported here. Please reopen if not.

**Comment by Barleyman** [comment]
> As of the next release, we will have a new trash plug-in. This plug-in works based on URLs, not IDs and there is no reset between restarts. Hopefully, it fixes all the issues reported here. Please reopen if not.

What if there are several tabs open with the same URL?

**Comment by rNeomy** [comment]
the extension will trash all the similar tabs when the oldest meet the time range. This is the best we can get. The ID-based selection only works if there is no restart since Chrome reassigns ids on a new instance. When a tab is discarded, it is not possible to inject any script into it so that we can have something to differentiate tabs. As far as I know, the only reliable parameter is the URL.

**Comment by dabat** [comment]
hey @rNeomy this is super exciting!!! thanks so much for the excellent product, and for the update about the new plug-in.
looking forward to trying that out!
thanks again.

**Comment by kgc35** [comment]
> 
> 
> @kgc35 have you restarted the browser during these hrs? Note that the timer resets itself if the browser restarts.

Sorry for the late reply. Yes I did restart my browser, it does work if I don't restart. 

However, I would please request this issue to be reopened. 

I do not think the proposed solution will work for me or other users. 
I always have multiple tabs from the same website. 
For example, if I have 5 tabs for Github, it does not make sense to close all 5 tabs if the oldest one has hit the time limit.
That first one I may have viewed 3 days ago, but the newest one only 30 mins ago. 

What other parameters do you have available to you?
Can you use the page title as the parameter? It is less common for pages to have the exact same title. 
If not, one solution is to save the title of page and the time of opening in a database.
Then if the browser is closed, try to find if an entry with that title already exists. 
If so, then append the previous time to the current time.

**Comment by Barleyman** [comment]
I don't think Github is much of a problem since the URL is different for each project. As long as the page isn't recognized by domain name only, that is, but somehow I doubt it's that simplistic.

As the man says, Firefox/Chrome et al assign a new tab ID on each browser start so it'd be pretty challenging to figure out identical URLs from each other. I'm not sure what actually happens on browser start, if the tabs are loaded from cache, I guess you could go all Facebook on trying to identify one from identical URLs.

**Comment by rNeomy** [comment]
The plugin is URL sensitive not domain sensitive. So as @Barleyman mentioned, the only faulty situation is when multiple tabs have the exact same URL.

btw, the entire code for this plugin is about 60 lines! so anybody interested can play around and try to find a better approach.
https://github.com/rNeomy/auto-tab-discard/blob/master/plugins/trash/core.js
