### ISSUE TITLE
Translation for Chinese (Taiwan)

### ISSUE THREAD

**Issue by Akiatc** [rNeomy/auto-tab-discard#190]
Hi, I've sent a request to join the translation team on Transifex for Chinese (Taiwan).
Please let me help with the translation. Thanks.

**Comment by rNeomy** [comment]
Sorry haven't got the confirmation email from transifex. Let me know if you are not on the team yet.

https://www.transifex.com/open-source-dev/auto-tab-discard/dashboard/
