### ISSUE TITLE
[Feature request] Option for manually discarding other tabs in window to also discard exempt tabs

### ISSUE THREAD

**Issue by tux93** [rNeomy/auto-tab-discard#191]
Currently the various "Discard other tabs" options do not affect tabs that are exempt (pinned tabs, tabs playing media, whitelist etc.)

It would be nice to have an option for manually triggering "Discard other tabs" to bypass those exceptions / the exceptions only to affect automatic discard.

**Comment by rNeomy** [comment]
As of the next release, you can use the Shift key on the popup interface and the extension will ignore discarding exceptions for all possible commands.
