### ISSUE TITLE
Discard Tabs when Window Inactive

### ISSUE THREAD

**Issue by jesse9212** [rNeomy/auto-tab-discard#194]
Possible to add feature:

Discard Tabs after X seconds when window is inactive

Load All/Background Tabs when window becomes active

**Comment by rNeomy** [comment]
As of the next release, we will have a new plugin on the options page.
```
Remove discarding of all tabs in the active window. If enabled, no tab in the active window will be discarded
```

combining this with the default options covers both feature requests.
