### ISSUE TITLE
Tabs being discarded automatically regardless of settings

### ISSUE THREAD

**Issue by Chkoupinator** [rNeomy/auto-tab-discard#197]
Hello,
I have had my settings like this for several months but ever since a couple days ago it started discarding any and every tab regardless of the fact that they shouldn't, even those who were pinned were getting discarded (even though I have an empty whitelist as seen in the screenshot below)
![image](https://user-images.githubusercontent.com/7254970/106766025-bd4c5f00-6639-11eb-8b3b-45e14eac29bc.png)

I'm not sure what's causing it I'm currently running Firefox Developer Edition 86.0b4 (64-bit) and have automatic updates enabled so it might have been a silent Firefox update causing it but I thought I'd let you know.

If there is any way to resolve this issue or to help in debugging I'm up for it, I'm considering disabling the addon completely now since I have only been using it for manual tab discarding myself...

**Comment by Luckz** [comment]
As far as I'm aware, the "proper" way of disabling automatic discarding is to replace the very first number, 600, with a 0.
This is my superstitious setup: 
![image](https://user-images.githubusercontent.com/224748/106779535-5fbf0f00-6647-11eb-9898-16945af68fdb.png)

**Comment by Chkoupinator** [comment]
> 
> 
> As far as I'm aware, the "proper" way of disabling automatic discarding is to replace the very first number, 600, with a 0.
> This is my superstitious setup:
> ![image](https://user-images.githubusercontent.com/224748/106779535-5fbf0f00-6647-11eb-9898-16945af68fdb.png)

I have done that as well but I still have tabs being discarded sometimes without any input from me

**Comment by rNeomy** [comment]
> I have done that as well but I still have tabs being discarded sometimes without any input from me

@Chkoupinator do you also get the favicon of the discarded tabs? If not, then your browser is discarding tabs when there is not enough memory
