### ISSUE TITLE
 0.4.0 update breaks in Firefox Developer 86.0b5

### ISSUE THREAD

**Issue by YayOrNay** [rNeomy/auto-tab-discard#198]
Auto Tab Discard stopped working for me with the 0.4.0 update a few days ago. 

Currently using Firefox Developer 86.0b5, with Auto Tab Discard 0.4.0 it stops discarding tabs, either automatically or manually when trying to "Discard All Other Tabs".

Went back to 0.3.7 which solved the problem immediately. As soon as I update it to 0.4.0, it doesn't work anymore.

**Comment by rNeomy** [comment]
I just check on FF 86.0b6 and "Discard All Other Tabs" works for me. Do you get any error on the console (Ctrl + Shift + J)? If not, you can enable the debugging and see the logs on the console.
