### ISSUE TITLE
Trash discarded tabs

### ISSUE THREAD

**Issue by LLKoder** [rNeomy/auto-tab-discard#199]
Hello,

I'm not sure that I right understand the setting "Trash (permanently delete) discarded tabs if they are inactive for about (in hours) (if enabled from the browser action's popup window)". What does it mean?
I understand that the setting will close all inactive tabs/windows in some time. It is unacceptable to me. I sometimes keep inactive tabs for a long time, after that I come to these tabs back.

If I right understand this setting how can I turn this setting off?

**Comment by youssefbellarbia** [comment]
I'm confused too. Can someone explain this setting please  ?

**Comment by LLKoder** [comment]
Maybe, the author would want to realise popup tips near each setting with detail information. I think It would be useful for everyone.

**Comment by pejotigrek** [comment]
came here to ask the same question. will be happy to see the explaination, as I always keep lots of tabs as some kind of notepad/todo list combo

**Comment by nspirov** [comment]
It is self-explained. There is a checkbox for this feature in the popup when you press the extension button. The checkbox is not checked. If you turn it on, then this setting will have meaning.
There are people who prefer to have old and forgotten tabs disappear. So they find this feature useful. It is OFF by default.

**Comment by LLKoder** [comment]
I didn't say this feature is not useful. Contrarywise I suppose this feature is very useful. Just I talked about a more clear description of this setting and other settings. This all what I said. 
And as we can see I'm not alone, who doesn't understand.
Thank you for your explanation. But I would expect to see this setting more logical formation and more understandable. Maybe I'm not right, but any case thank you again.

**Comment by kgc35** [comment]
@rNeomy The newest version does not have a checkbox for trashing. How can I tell it is working? I set it to trash 24 hr old tabs, but I still have over 100 tabs. It does not seem to be working.

I do not close my browser during the 24 hr period. 

Also, how can I access the logs? I cannot figure out how.

**Comment by rNeomy** [comment]
@kgc35 trash is now a plug-in. Go to the options page, on the plug-ins section turn it on or off.

> Also, how can I access the logs? I cannot figure out how.

You need to open chrome://extensions on a browser tab. Turn the developer mode on, and then press the "Background.html" link of this extension. Go to the console tab and if logs in enabled, you should see longs get printed by this extension.

**Comment by kgc35** [comment]
> 
> 
> @kgc35 trash is now a plug-in. Go to the options page, on the plug-ins section turn it on or off.
> 
> > Also, how can I access the logs? I cannot figure out how.
> 
> You need to open chrome://extensions on a browser tab. Turn the developer mode on, and then press the "Background.html" link of this extension. Go to the console tab and if logs in enabled, you should see longs get printed by this extension.

ok thanks, how can I do this in Firefox?

**Comment by rNeomy** [comment]
In FF, use your browser console (Ctrl + Shift + J), or go to the about:debugging and press the "Inspect" button of this add-on

**Comment by kgc35** [comment]
Thanks, I found it. 
What is the log entry for Trashed (Permanently discarded) tabs? I want to check if it is working. 

number of tabs to get discarded 2
number of tabs being discarded 2
trash.observe is called

I see these entries, but what would it say when tabs are Trashed?

**Comment by rNeomy** [comment]
@kgc35 there was no logging. I added a new one; https://github.com/rNeomy/auto-tab-discard/blob/master/plugins/trash/core.js#L40
