### ISSUE TITLE
Use regexp for url in exception list

### ISSUE THREAD

**Issue by Gnustier** [rNeomy/auto-tab-discard#20]
Could you please , 
make the exception list able to use the regular expression for specific URL ?
If no , 
make the exception list able to use the wildcard character for specific URL ?

**Comment by rNeomy** [comment]
Sure, from the next release use `re:reg-exp` in the whitelist box for URL regular expression matching.

**Comment by megamorphg** [comment]
@rNeomy does this support full regex or is there something special?
I'm trying to whitelist the following URL
https://mail.google.com/mail/u/0/?zx=rqeorersgjbd#inbox

So I use the following regex but it doesn't work:
re:https:\/\/mail\.google\.com\/mail\/u\/0.*

**Comment by rNeomy** [comment]
@megamorphg I just checked this rule on the `0.6.0` release, and it works fine for me. Please share your exception list rules.

**Comment by rNeomy** [comment]
@megamorphg on the `0.6.0` release, if the Gmail tab is active and the rule matches the address, the popup's "Keep Tabs for This Site" must be checked.

**Comment by rNeomy** [comment]
@megamorphg 

> It looks like it should now work

So we are good?

> It doesn't escape the first two slashes

There is no need to escape "/". It is meant to work with `new RegExp`
https://github.com/rNeomy/auto-tab-discard/blob/master/v3/worker/core/utils.mjs#L20
<img width="130" alt="Screenshot 2022-04-13 at 00 56 14" src="https://user-images.githubusercontent.com/14104614/163103273-037fb38c-fd8e-4170-a727-e3ec882fee6f.png">
