### ISSUE TITLE
Tab State not maintained in Chrome 88

### ISSUE THREAD

**Issue by rpratik786** [rNeomy/auto-tab-discard#201]
As per Chrome 88, Auto Tab Discard doesn't maintain the tab state when restored. I have tried other extensions like Tabby which use Chrome's Discard tab API and they seem to work fine. Can you please have a look?

**Comment by rNeomy** [comment]
I am not able to reproduce this. Have you tried the extension on a clean profile?

**Comment by rpratik786** [comment]
Worked on a clean profile and different system
