### ISSUE TITLE
0.4.0 not working in Firefox 85.0.1

### ISSUE THREAD

**Issue by rasoolsomji** [rNeomy/auto-tab-discard#203]
Firstly, I'm a tremendous fan of the extension.

But on Firefox **85.0.1** (64-bit) running on **Ubuntu 20.04** (technically Pop OS but it's Ubuntu-esque) several of the features didn't work.

"Discard Tab" - to discard the tab currently selected **did** work but the other options (discard tabs to the left, discard tabs to the right, discard all other tabs) **did not** work.

There was nothing in the browser console when clicking those failing options, not even when I enabled debugging logging.

All features were working on version 0.3.7 and having rolled back to 0.3.7 they continue to all work.

Sorry that this report is so vague, I was even in two minds about whether to create an issue at all, but it made me realise how dependent I'd become on this extension so I wanted to contribute.

I'm happy to re-upgrade to 0.4.0 to provide you more information

**Comment by donnchawp** [comment]
The extension has been updated to 0.4.1 but I don't think the problem has been fixed. (Tested on Firefox 85.0.2 on macOS too)

**Comment by rNeomy** [comment]
To things to try

1. Open the popup view and use the Shift key while pressing the "Discard other tabs" options. This will bypass all restrictions and force discarding all tabs
2. Try to export all your custom settings and then press the restart button and do a browser restart. Now set the timeout to 60 seconds and set the number of tabs to zero. See it works or not after a minute.

**Comment by donnchawp** [comment]
Thanks @rNeomy. I tried pressing shift but "discard all other tabs" didn't work. The second suggestion is a little more drastic but I'll give it a go later.

**Comment by Wrizz** [comment]
I have similar problem, only "Discard tab" in context menu works, other options don't work.
Nothing else works even doing it via button on toolbar doesn't work. 
It does work if I hold CTRL while pressing an option using button on toolbar though.

**Comment by kgc35** [comment]
I also have it not working now, with 0.4.1 and latest Firefox. None of my tabs are getting trashed. 
It is also related to Leechblock, which I have started a new issue for. 

I have rolled back to 0.3.7 and see if it is working again.

**Comment by donnchawp** [comment]
I tried setting dom.webnotifications.enabled to true (in about:config) as suggested in #206 but it didn't work for me in 0.4.2. Unfortunately I have too many tabs open to clear out my profile but will keep looking.

**Comment by donnchawp** [comment]
I created a new profile, it opened in a new window and unfortunately none of the browser tabs were discarded automatically.
dom.webnotifications.enabled is set to true, by default.
The "Discard other tabs in this window" command did work at least.

**Comment by donnchawp** [comment]
I was mistaken. It does seem to be auto discarding tabs now.Thanks for fixing that.

**Comment by rasoolsomji** [comment]
@rNeomy This seems to be working great in v0.4.2 (Firefox v87.0) so feel free to close this issue :)
