### ISSUE TITLE
Timeout Discards Not Happening

### ISSUE THREAD

**Issue by obit11** [rNeomy/auto-tab-discard#204]
I'm running the Chrome Browser on Ubuntu 20.04. I have the auto-tab-discard set at 300 seconds, but looking at the discard table, nothing ever gets discarded. I can select discard this tab from the extension menu, and it works showing up as "discarded [external]" in the table, but none of the tabs discard due to the timeout.

I don't know if this is a bug, or user error on my part.

**Comment by rNeomy** [comment]
go to chrome://extensions and turn the developer mode on. Now open the options page and turn on the debugging mode. You will get logs in the background page of chrome://extensions. Please share the logs for one interval

**Comment by Liniert** [comment]
Hello,
I turned on the developer mode, went to the addon options and activated "show protocols", the first entry under miscellaneous.
Then I saved the options, went back to the extensions window and clicked on the background page.
A new window opens, titled Developer Tools, there I checked "console" and "network > all".

Now I open a new tab, open the Auto Tab Discard tool (0.4.1) and click on "discard this tab".
And nothing happens. The tab doesn't discard and I don't see anything happen in the Developer Tools either.

Am I doing something wrong?

**Comment by rNeomy** [comment]
> Now I open a new tab, 

You need to load a URL first (e.g. www.google.com). This extension does not discard blank tabs.

Since you are on Chrome, it is pretty simple to create a new profile. Can you also give the extension a try on a clean profile?

**Comment by rNeomy** [comment]
> I don't see anything happen in the Developer Tools either.

Don't you get some logs being printed on the "console" tab?

**Comment by Sada-Mio** [comment]
Having same issue with WIN10 FF v85.0.2 

Discard inactive tabs after (in seconds) isn't working

**Comment by rNeomy** [comment]
@Sada-Mio can you try on a clean profile?
https://support.mozilla.org/en-US/kb/profile-manager-create-remove-switch-firefox-profiles

**Comment by Sada-Mio** [comment]
@rNeomy clean profile tabs are auto discarding. 

However, can't figure out why my main profile doesn't. Tried disabling all my extensions except auto tab discard. 

Enabled logs but don't see anything in the browser console.

**Comment by Sada-Mio** [comment]
@rNeomy 

changing **dom.webnotifications.enabled** to **true** fixed auto discarding. 

So my issue is the same with https://github.com/rNeomy/auto-tab-discard/issues/206

**Comment by rNeomy** [comment]
I am going to push a new update to fix this issue. Thanks for the confirmation.

**Comment by Liniert** [comment]
Hi, I just wanted to give the feedback that with version 0.4.2, it works again.
I can discard tabs again and the logging now actually works.

Thank you for fixing it!

**Comment by Liniert** [comment]
@rNeomy It appears that the problem has returned. I am currently on version 0.4.4.2 using Chrome.
But this time around the console seems to work and shows:

For a manual discard:

`"onMessage request received" {method: "tabs.query", queryInfo: {…}}    background.js:77`
`"onMessage request received" {method: "storage", prefs: {…}}    background.js:77`
`"onMessage request received" {method: "popup", cmd: "discard-tab", shiftKey: false}    background.js:77`
`Uncaught (in promise) ReferenceError: interrupts is not defined    menu.js:94`
`at onClicked (menu.js:94)`
`at query.then.tabs (menu.js:298)`
`at <anonymous>`
![menujs](https://user-images.githubusercontent.com/60542762/114764697-c7828c00-9d53-11eb-94d2-05345d3d5293.png)


For a timed discard:
`"alarm fire" "number.check" "number.check"    background.js:77`
`Uncaught (in promise) ReferenceError: interrupts is not defined    number.js:29
    at Object.number.check (chrome-extension://jhnleheckmknfcgijgkadoemagpecfol/modes/number.js:29:3)
    at chrome.alarms.onAlarm.addListener.alarm (chrome-extension://jhnleheckmknfcgijgkadoemagpecfol/modes/number.js:227:12)
    at EventImpl.dispatchToListener (extensions::event_bindings:403:22)
    at Event.publicClassPrototype.(anonymous function) [as dispatchToListener] (extensions::utils:138:26)
    at EventImpl.dispatch_ (extensions::event_bindings:387:35)
    at dispatchArgs (extensions::event_bindings:260:26)
    at dispatchEvent (extensions::event_bindings:269:7)`
![numberjs](https://user-images.githubusercontent.com/60542762/114764633-b76aac80-9d53-11eb-8243-7c7ebee88048.png)

**Comment by rNeomy** [comment]
@Liniert that's weird! This error means the `plugins.js` is not loaded yet. Do you get this error on every manual discarding?

**Comment by Liniert** [comment]
@rNeomy
My browser just updated to the newest version, 0.4.5.1, and now the functionality is back again.

Although I still get a warning message:

When manually discarding a single tab or for a timed discard:
`plugins module is not loaded    menu.js:100`

When I manually discard multiple (left/right) tabs:
`plugins module is not loaded    menu.js:100`
`plugins module is not loaded    number.js:33`

But I don't know how to investigate this further to gather useful information.

**Comment by rNeomy** [comment]
@Liniert what is the output when you type `interrupts` in the console tab followed by pressing the Enter key?

**Comment by Liniert** [comment]
@rNeomy
`Uncaught ReferenceError: interrupts is not defined    VM103:1
    at <anonymous>:1:1`
"VM103:1" contains a single line that says "interrupts". The page is yellow, instead of being white like in .js or .html files.
And the number changes depending on the website that I have open.
Could be that there is something funny going on with my browser. Maybe I should reinstall it.

**Comment by rNeomy** [comment]
> Could be that there is something funny going on with my browser. Maybe I should reinstall it.

No, I don't think so. Your browser seems fine to me. However, I am still not sure why the `plugins.js` is not loaded.

Please do a soft restart by inserting `chrome.runtime.reload()` in the console tab followed by the Enter key. Do you get any warnings or errors?

**Comment by Liniert** [comment]
@rNeomy After using that command I noticed that I get an error the moment I open the console or when I use your reload command:

`Uncaught SyntaxError: Unexpected token import              plugins.js:14`
![plugins_js_SyntaxError](https://user-images.githubusercontent.com/60542762/115224306-3b2deb80-a0fc-11eb-9bb8-fba050201938.png)

**Comment by rNeomy** [comment]
Looks like that your Chrome does not support dynamic importing. What is your Chrome version?
