### ISSUE TITLE
[**Solved**] [v0.4.1] [FF 85.0.2] Not working ...

### ISSUE THREAD

**Issue by rprimus** [rNeomy/auto-tab-discard#206]
Thu Feb 18 22:39:42 GMT 2021

<details>
<summary>OS details</summary>

ProductName:	Mac OS X
ProductVersion:	10.15.7
BuildVersion:	19H524

FF: Mozilla Firefox 85.0.2 (64-bit)

auto-tab-discard: 0.4.1
</details>

From `about:debugging#/runtime/this-firefox`:
```
Warning details

Reading manifest: Warning processing background.persistent: Event pages are not currently supported. This will run as a persistent background page.
```
```
Warning details

Reading manifest: Warning processing background.persistent: Event pages are not currently supported. This will run as a persistent background page.
```

The only action that works: 

For any tab apart from current tab: 
  `<Tab head> -> <right click> -> Auto Tab Discard -> Discard Tab`

**Comment by rprimus** [comment]
Fri Feb 19 04:12:37 GMT 2021

For tabs that should (/I expect to) be `discarded`, the `auto-tab-discard` button in toolbar is coloured `blue` and shows message:
`metadata fetch error`.

**Comment by rprimus** [comment]
Sat Feb 20 07:19:27 GMT 2021

Last '`working`' version: 0.3.7.

**Comment by kgc35** [comment]
> 
> 
> Sat Feb 20 07:19:27 GMT 2021
> 
> Last '`working`' version: 0.3.7.
> 
> v0.3.7 also shows the same warnings (as noted in the first [#206 (comment)](https://github.com/rNeomy/auto-tab-discard/issues/206#issue-811544129) above).

so you are saying 0.3.7 is working, but still shows the errors?
But 0.4.1 isn't working? I have rolled back to see myself.

**Comment by rprimus** [comment]
Mon Feb 22 04:48:20 GMT 2021

`v0.3.7` is 'working' in that it is actually suspending/discarding un-used tabs.
`v0.3.7` shows the same 'warnings' in `about:debugging#/runtime/this-firefox`.

`0.4.0` and `0.4.1` do not work.

**Comment by rNeomy** [comment]
@rprimus can you try on a clean profile? https://support.mozilla.org/en-US/kb/profile-manager-create-remove-switch-firefox-profiles

**Comment by rprimus** [comment]
Tue Feb 23 08:33:48 GMT 2021

@rNeomy - with a clean profile, `v0.4.1` works.  (There are still the two warnings in `about:debugging#/runtime/this-firefox`.)

Will:
1. Close this issue
2. Continue using `v0.3.7` until I can determine what in causing the conflict with the changes made in `v0.4.0`.

**Comment by rprimus** [comment]
Tue Feb 23 09:59:11 GMT 2021

Reopening to request using `git tags` for the versions (as requested in https://github.com/rNeomy/auto-tab-discard/issues/205).

This would make it easier to do a comparison between the `versions` to see what is causing the problems related to this issue (and issues: https://github.com/rNeomy/auto-tab-discard/issues/198, #203, #204).

**Comment by rprimus** [comment]
Tue Feb 23 11:54:06 GMT 2021

@rNeomy : FYI:
https://github.com/rprimus/auto-tab-discard/compare/v0.3.7...rprimus:v0.4.0-ff

**Comment by rprimus** [comment]
Tue Feb 23 18:09:06 GMT 2021

### Solved.

@rNeomy :
Thanks for the `clean profile` hint!   The cause of the `problem` is preference:

```
user_pref("dom.webnotifications.enabled", false);
```

Setting this to `true` resolves the issue.

What were the changes made that use `web notifications`?

**Comment by kgc35** [comment]
> 
> 
> Tue Feb 23 18:09:06 GMT 2021
> ### Solved.
> 
> @rNeomy :
> Thanks for the `clean profile` hint! The cause of the `problem` is preference:
> 
> ```
> user_pref("dom.webnotifications.enabled", false);
> ```
> 
> Setting this to `true` resolves the issue.
> 
> What were the changes made that use `web notifications`?

Thanks, how can the rest of us solve this problem?
Is this something I need to do manually or it will be fixed in the extension?

**Comment by rNeomy** [comment]
@rprimus thanks for the hint. @kgc35 wait for the new FF-only release
