### ISSUE TITLE
Trashing tabs not working with Leechblock. 

### ISSUE THREAD

**Issue by kgc35** [rNeomy/auto-tab-discard#207]
Hello, I am using Leechblock in order to manage my time online. However, it seems like this extension does not work with Leechblock. Can this be fixed? The tabs get blocked, but then they are not trashed. 

An example URL with Leechblock would be something like this:

> moz-extension://f5fded8d-ae73-4221-bad7-cc12c260b968/blocked.html?1&https://www.quora.com/

This is the extension: 
https://www.proginosko.com/leechblock/

It seems like these URLs are not recognized by Auto Tab Discard, but I seem to remember it working in previous versions of the extension.

**Comment by rNeomy** [comment]
No extension can access pages from other extensions (`moz-extension://...`). I am not sure why it even gets discarded!

**Comment by kgc35** [comment]
I can confirm that Version 0.3.7 did discard moz-extension:// tabs.
The newer versions do not. 

However, I see that Version 0.4.1.1 has released.
I will be testing it now and let you know if it works.

**Comment by rNeomy** [comment]
The discarding is meant for HTTP pages. So it is better not to discard anything internal (it might break things). Each developer can implement this feature for their own internal pages with a single line of code. So please contact the Leechblock developer instead.
