### ISSUE TITLE
Please remove "zh" in language

### ISSUE THREAD

**Issue by thomassth** [rNeomy/auto-tab-discard#210]
There are many Chinese "languages" (technically, different scripts of the same language), zh-CN and zh-TW are the most common, among many others.

No variant should be set as "zh". Making either one in "zh" is commonly seen as a political pledge for or against PRC, which only recognizes zh-CN and had a loaded history and policies of purging other writing Chinese scripts. [There is an entire wiki page on this subject.](https://en.wikipedia.org/wiki/Debate_on_traditional_and_simplified_Chinese_characters)

Remove zh and retain zh-CN, zh-TW is the easiest workaround on the matter.

Transifex should allow you to turn off support for zh while allowing zh-CN, zh-TW, and other zh variants. [Signal does that. ](https://www.transifex.com/signalapp/)

**Comment by rNeomy** [comment]
Thanks for the explanation. It is removed.
