### ISSUE TITLE
Firefox 86.0 - add-on signing blocks Auto-tab-discard

### ISSUE THREAD

**Issue by 4t0mX** [rNeomy/auto-tab-discard#213]
Hey guys,
Yesterday auto-tab-discard has been blocked by Firefox add-on signing it seems as it now appears in the "deactivated" modules and extensions...
Anybody else have this issue?
Thank you

**Comment by kgc35** [comment]
I am on Firefox 86 and don't have this issue.

**Comment by rNeomy** [comment]
I am not able to reproduce too. Please reopen if you have more info.
