### ISSUE TITLE
Settings loaded from managed storage not applied

### ISSUE THREAD

**Issue by ConnorJC3** [rNeomy/auto-tab-discard#216]
I'm setting options via managed storage (https://add0n.com/tab-discard.html#faq10). These changes show up in the Auto Tab Discard settings UI, but do not actually appear to take affect until the user manually enters the UI and clicks "Save Options".

This is not desirable, as the point of using managed storage to configure options to to transparently configure settings without needing user interaction.

Browser: Firefox Nightly 89.0a1 (2021-03-25) (64-bit)
OS: Linux (x86_64)
ATD Version: 0.4.2 (latest on AMO)
Tested on a fresh profile with only ATD, no other extensions.

**Comment by rNeomy** [comment]
Can you share the JSON file?

**Comment by ConnorJC3** [comment]
@rNeomy as far as I can tell, literally any JSON produces this behavior (i.e. I cannot figure out a way not to trigger it).

Minimal example:

`~/.mozilla/managed-storage/{c2c003ee-bd69-42a2-b0e9-6f34222cb046}.json`:
```json
{
  "name": "{c2c003ee-bd69-42a2-b0e9-6f34222cb046}",
  "description": "ignored",
  "type": "storage",
  "data": {
    "faqs": false
  }
}
```

`/etc/firefox/policies/policies.json`:
```json
{
  "policies": {
    "ExtensionSettings": {
      "{c2c003ee-bd69-42a2-b0e9-6f34222cb046}": {
        "install_url": "https://addons.mozilla.org/firefox/downloads/latest/auto-tab-discard/latest.xpi",
        "installation_mode": "normal_installed"
      }
    }
  }
}
```

Expected behavior: FAQ does not show after extension is auto installed via the policy.
Actual behavior: FAQ page shows. FAQ setting is off in UI but does not appear to take effect until "Save Options" in UI is clicked.

**Comment by rNeomy** [comment]
Thanks for the report. Should have been fixed. Reopen if not after the next update.
