### ISSUE TITLE
Tabs unsuspend when exiting fullscreen (Firefox 87, Ubuntu 20.04)

### ISSUE THREAD

**Issue by pkoby** [rNeomy/auto-tab-discard#217]
After it seems the latest Firefox update, discarded tabs unsuspend when I leave a fullscreen video. This happens on multiple websites (Youtube, Twitch, Twitter), so it seems to be the act of going from fullscreen to not. Note that this doesn't happen to me when I go fullscreen with F11, just when I do it with video players, so it's possible something to do with Firefox's full-screen-api (adjusting some such settings in about:config didn't fix it).

**Comment by rNeomy** [comment]
I am not able to reproduce this on Mac. Please try on a clean profile and reopen if you can reproduce.

**Comment by pkoby** [comment]
I just tested another possibility: it only unsuspends pinned tabs. Full tabs are unaffected.

I'll try to test this on a fresh profile at some point and let you know if it still happens.

**Comment by rNeomy** [comment]
https://github.com/rNeomy/auto-tab-discard/issues/219
