### ISSUE TITLE
Media playing

### ISSUE THREAD

**Issue by rayman89** [rNeomy/auto-tab-discard#22]
The addon seems to not notice when media is playing or not. It does not unload the tab is there is a video even if the video was never played like for example in youtube.

**Comment by rNeomy** [comment]
Is is on FF58? You need FF59 for YouTube discarding. To test if the discarding signal is sent or not, enable the logging from the options page and check the console for logs.

**Comment by rayman89** [comment]
I'm on firefox developer version latest update. All works perfectly except for the pages with videos that the addon decides not to unload but there is no media playing there. Youtube was an example.

**Comment by rNeomy** [comment]
Okay then, enable the debugging from the options page and force discard a tab and see what you get on the web console.

You can detach the web console from the page and then switch to another page to fire discarding.

**Comment by rayman89** [comment]
I got this 

TypeError: Function.prototype.call called on incompatible undefined[Conocer más]
22:2:477
Using //@ to indicate sourceMappingURL pragmas is deprecated. Use //# instead[Conocer más]
22:4
Using //@ to indicate sourceMappingURL pragmas is deprecated. Use //# instead[Conocer más]
22:4
Error: Permission denied to access property "localName"[Conocer más]
22:47:7
Content Security Policy: La directiva ‘child-src’ es obsoleta. Por favor use la directiva ‘worker-src’ para controlar workers o la directiva ‘frame-src’ para controlar frames respectivamente.

TypeError: Function.prototype.call called on incompatible undefined[Conocer más]
issues:2:477
Using //@ to indicate sourceMappingURL pragmas is deprecated. Use //# instead[Conocer más]
issues:4
Using //@ to indicate sourceMappingURL pragmas is deprecated. Use //# instead[Conocer más]
issues%20line%202%20%3E%20eval:4
Error: Permission denied to access property "localName"[Conocer más]
issues%20line%203%20%3E%20Function:47:7

Also noticed that when force discarding current tab the addon just switches focus to an other tab but does not unload the previously current tab.

**Comment by rNeomy** [comment]
> Also noticed that when force discarding current tab the addon just switches focus to an other tab but does not unload the previously current tab

You need to wait for a few seconds. This is an intentional delay.

**Comment by fermulator** [comment]
The feature works for me Firefox73 Linux; Presumably ticket is obsolete?

**Comment by grahamperrin** [comment]
+1 to closing this issue.
