### ISSUE TITLE
"Keep tabs for this site 'Session'" tabs - discarded anyway

### ISSUE THREAD

**Issue by asem63** [rNeomy/auto-tab-discard#220]
"Keep tabs for this site 'Session'" option no longer works in new (0.4.3) version of chrome extension.
Tabs that are marked with this option - discarded anyway.

**Comment by rNeomy** [comment]
Can you reproduce after a restart?

**Comment by asem63** [comment]
>Can you reproduce after a restart?
Yes

Also, update on issue:
whitelisted for session site is actually somehow removed from whitelist after ~1 minute and option "Keep tabs for this site 'Session'" is active(clickable) again for specified site.

Steps to reproduce:
1) Open 2-3 tabs of site "foo"
2) Press "Keep tabs for this site 'Session'"
3) Open site "bar" in another tab and wait for 1-2 minutes
4) Return to site "foo" and observe that "Keep tabs for this site 'Session'" is clickable again

**Comment by rNeomy** [comment]
Thanks for the report. Should be fixed by 0.4.3.1 release.
