### ISSUE TITLE
[Feature request] Keyboard shortcuts

### ISSUE THREAD

**Issue by copergopher934** [rNeomy/auto-tab-discard#222]
Hi, I find myself having to manually discard some tabs on domains difficult to put in a use case available within the addon options, so I was wondering if it was possible to introduce some form of keyboard shortcuts control for at least the basic functions of discarding a single tab or a group of them?

**Comment by rNeomy** [comment]
Have you checked chrome://extensions/shortcuts?

**Comment by copergopher934** [comment]
Thanks for the quick response, I just checked it even though I barely ever use chrome, thanks. Is there an analog for this in firefox though?

**Comment by copergopher934** [comment]
I just checked it, also found the firefox analog as well that I never knew existed, thank you very much, problem solved!
