### ISSUE TITLE
Bookmark favicon automatically changes to ATD's discarded favicon

### ISSUE THREAD

**Issue by dannyfelix** [rNeomy/auto-tab-discard#223]
Not sure if this is more of an issue with Chrome than the extension itself but I keep having an issue where the favicon of my bookmarks change to that of the discarded favicon (I've attached an image below), I used to use The Great Suspender and I don't think I had this issue, despite them having favicons to note when a tab is suspended. 

![chrome_qLbEIpxL8w](https://user-images.githubusercontent.com/25198579/113876329-8ae0ee80-97af-11eb-8406-050941b3976b.png)

Does anyone know of a way to stop this without disabling the discarded favicon styling as a whole? Thanks

**Comment by rNeomy** [comment]
As far as I know, there is no visual API yet to alter the tab's appearance in Chrome. So this extension manually alters the page favicon just before discarding a tab. 

TGS redirects to an internal page instead of discarding so the story is different.

**Comment by rNeomy** [comment]
There will be a new option on the options page to prepend a symbol to the discarded tabs instead of altering the favicon (e.g. 💤 or ⏻︎). Since there is no styling API yet for tabs, I am closing this bug for now.
