### ISSUE TITLE
New version 0.4.3 seems to ignore any discard rules

### ISSUE THREAD

**Issue by xannasavin** [rNeomy/auto-tab-discard#224]
Following the thread of Kevin M. Dean on https://add0n.com/tab-discard.html where I can't post an answer:

> Version 0.4.3 seems to discard tabs very quickly and not use the value entered in "Discard inactive tabs after (in minutes)". I have it set to 10 minutes, yet I have tabs discard within seconds. I have to whitelist a site to keep that from happening. I'm going to try entering zero to disable to see if that works any different.

==>

I notice the very same behaviour since the new version:
Tabs are discarded almost immediatley (not like after the 10mins I set) and also tabs I added to the session list are discarded. this is pretty annoying. It also seems not to care anymore about form entries on a page anymore, lost some created posts due to this when I switched to another tab and my tab with the filled form was just discarded...

**Comment by rNeomy** [comment]
Please update to 0.4.4.2 and report back
https://chrome.google.com/webstore/detail/auto-tab-discard/jhnleheckmknfcgijgkadoemagpecfol

**Comment by xannasavin** [comment]
yep, seems to be gone, thank you!
