### ISSUE TITLE
general.useragent.override breaks Auto Tab Discard

### ISSUE THREAD

**Issue by Harshsrcc** [rNeomy/auto-tab-discard#225]
@rNeomy The extension has suddenly stopped working for me on Firefox Nightly (890a1) on Windows 10. About:Debugging shows 2 errors:

1. Reading manifest: Warning processing background.persistent: Event pages are not currently supported. This will run as a persistent background page.
2. Reading manifest: Warning processing storage: An unexpected property was found in the WebExtension manifest.

**Comment by Harshsrcc** [comment]
Found the culprit. Apparently, spoofing user agent, with general.useragent.override breaks Auto Tab Discard. Can it be made to work with useragent override? 

I'll update the issue title.

**Comment by rNeomy** [comment]
Thanks for the report. Should get fixed by the next release. Reopen if not.
