### ISSUE TITLE
[Feature Request] Auto-Discard new tabs

### ISSUE THREAD

**Issue by zaser321** [rNeomy/auto-tab-discard#226]
Is it possible to add an option to auto discard new tabs.
I sometimes read a page with a lot of links and sources that I want to chek out later so I just open them in a new tab.

Also (not in title), is there a way to make Chrome's right clicking on a tab to list also as an option "Discard tab/group"?

**Comment by rNeomy** [comment]
> Is it possible to add an option to auto discard new tabs.

Not exactly what you needed though we already have a context menu item for links to open a tab in the discarded mode. 
Anyhow we can have a new plug-in for this.

> Also (not in title), is there a way to make Chrome's right clicking on a tab to list also as an option "Discard tab/group"?

Unfortunately not! Chrome does not allow extensions to add items to this context.

**Comment by grahamperrin** [comment]
Thanks, the feature is not yet working for me (tested with <https://bsd-hardware.info/?probe=cdeafa0952> opened into a new tab). Maybe I need to quit then start Firefox 88 for it to become effective …

**Comment by grahamperrin** [comment]
Also, please: is it possible for this new plug-in (or a separate plug-in) to open a tab in the discarded state **without** first loading the tab? 

Whilst the _load first_ approach is ideal when it's desirable to gain the title of a page, there's also a use case that (for performance) requires nothing more than the URL in the discarded tab. 

Thanks

**Comment by rNeomy** [comment]
>  the feature is not yet working for me

Right. I forgot to check in FF. We are having two issues here:

1. `chrome.tabs.onCreated.addListener` is called too soon when the page does not have a URL so the extension gets permission denied when trying to inject the code. This is fixed now by overwriting this function.
2. Even when the page has a DOM, still discarding the tab ruins the tab. So we needed to wait even more. 

So in FF, this plug-in works as follows:
The extension waits for the tab to have a valid title. Then discards it after one second (this still may cause issues on low-performance systems). Please give the latest commit a try and report back.

**Comment by rNeomy** [comment]
> Also, please: is it possible for this new plug-in (or a separate plug-in) to open a tab in the discarded state without first loading the tab?

Not really. Even after a one-second delay still discarding is not stable. However, you can use the `Open Link in New Discarded Tab` to discard immediately.

**Comment by grahamperrin** [comment]
> … Please give the latest commit a try and report back.

Please don't think me lazy but I'll probably await the next release. Thanks

**Comment by grahamperrin** [comment]
https://github.com/piroor/treestyletab/issues/2880

**Comment by grahamperrin** [comment]
For clarity

----

☑ **Discard all newly opened inactive tabs after they get loaded** 

* also known as _Auto-Discard new tabs_
* is **not** affected by <https://github.com/piroor/treestyletab/issues/2880>, as far as I can tell.

----

**Open in New Discarded Tab** (link context menu option)

* **is** affected by https://github.com/piroor/treestyletab/issues/2880
* **does not load** before discarding.

**Comment by grahamperrin** [comment]
https://github.com/rNeomy/auto-tab-discard/issues/226#issuecomment-826041623

> … Please give the latest commit a try and report back.

Thank you. The feature does seem to work reliably for me, with multiple profiles, with version `0.4.7` of the extension. 

If I understand correctly, using this feature effectively ignores the list of exceptions: 

* pages that should be _never_ discarded after loading are, instead, discarded _one second_ after loading.

**Comment by grahamperrin** [comment]
#231
