### ISSUE TITLE
Popup window too small when button is in overflow (Firefox)

### ISSUE THREAD

**Issue by Keefaetana** [rNeomy/auto-tab-discard#228]
![ATB window](https://user-images.githubusercontent.com/16086693/115963924-6e241500-a52a-11eb-9a86-8171b686e464.png)

When the Auto Tab Discard toolbar button is put in the Overflow Menu, the window which pops up when clicking on the button is too small and has scroll bars (see screenshot). It's mostly a visual annoyance, but clicking on the Keep This Tab For This Session box becomes very difficult when the box is barely visible without scrolling horizontally. No such issue when the ATB button is not in the overflow.

**Comment by rNeomy** [comment]
Should have been fixed by the new release. Thanks for the report.
