### ISSUE TITLE
"Discard all unpinned tabs on a browser or extension startup" setting does not appear to be functioning

### ISSUE THREAD

**Issue by mute2120** [rNeomy/auto-tab-discard#230]
Upon closing and opening FF, with this setting activated, no tabs get discarded, even when there are unpinned, non-discarded tabs in the session.

Firefox 89, Windows 10 Pro.

Auto-Tab-Discard settings .json attached.

[auto-tab-discard-preferences.zip](https://github.com/rNeomy/auto-tab-discard/files/6395628/auto-tab-discard-preferences.zip)

**Comment by defi-addict** [comment]
I've been experiencing the same issue.

**Comment by rNeomy** [comment]
I am pushing a new fix. Thanks for the report.

**Comment by mute2120** [comment]
> 
> 
> I am pushing a new fix. Thanks for the report.

Thanks for the active response, though this doesn't seem to have been fixed for me. Same issue still persists.
