### ISSUE TITLE
Control-Click, the tab is improperly discarded around one second after loading

### ISSUE THREAD

**Issue by grahamperrin** [rNeomy/auto-tab-discard#231]
After experimenting with the relatively new feature: 

☑ **Discard all newly opened inactive tabs after they get loaded**

– I disabled the feature, and saved my preferences. 

Despite saving preferences: the feature seems to persist, wherever there's <kbd>Control</kbd>-click on a link. 

Screenshots and screen recording taken. I don't have time to investigate right now (sorry – I'm at work) so to avoid disruptions, I have disabled the extension.

**Comment by grahamperrin** [comment]
Here's a new screen recording, demonstrating the bug with a refreshed profile: 

https://user-images.githubusercontent.com/192271/116712847-2b4fba80-a9cc-11eb-97ef-5ec0278a9d4c.mp4

**Comment by rNeomy** [comment]
Thanks for the report. This is an FF-only issue and will be fixed by the next release.

**Comment by grahamperrin** [comment]
Thanks for fixing so quickly! Amazing.

**Comment by grahamperrin** [comment]
Re: #163 and https://addons.mozilla.org/en-CA/firefox/addon/auto-tab-discard/versions/

https://addons.mozilla.org/en-CA/firefox/addon/auto-tab-discard/versions/0.4.8/updateinfo/ mentions <https://github.com/rNeomy/auto-tab-discard/issues/248> but not this #231, the fix for which was committed after the previous version `0.4.7` was released. 

In the absence of a fix for this bug (prior to `0.4.8`) I can not recall symptoms recurring.

**Comment by rNeomy** [comment]
@grahamperrin I just added this fix to the release note of v0.4.8
