### ISSUE TITLE
Change favicon of discarded tabs (if possible) checkbox is ignored

### ISSUE THREAD

**Issue by awused** [rNeomy/auto-tab-discard#232]
Firefox 87, ATD 0.4.7

I've got `Change favicon of discarded tabs (if possible)` disabled, but with the latest update this setting is ignored and it always appends the "zzz" icon to discarded tabs. Changing the setting does nothing; regardless of whether the box is checked or not the behaviour is the same.

**Comment by anghelos** [comment]
Firefox developer 89.0b6 (64-bit), ATD 0.4.7

I have the same problem, "Zzz"s started appearing on my tabs since the latest update. I find the greyed-out versions much clearer and more appealing.

**Comment by jonathonf** [comment]
Also confirming on Nightly 90.0a1.

**Comment by rNeomy** [comment]
to hide the`Zzz`, empty the "Prepends a symbol to the discarded tabs" option
to show the greyed-out favicon, check "Change favicon of discarded tabs (if possible)"

**Comment by anghelos** [comment]
Actually, the fact that it says "Prepends" instead of "Prepend", along with the lack of a checkbox makes it look like an explanation of the above option, instead of an option by itself.

**Comment by rNeomy** [comment]
> Actually, the fact that it says "Prepends" instead of "Prepend"

Fixed!

**Comment by awused** [comment]
Yeah I think the "Prepends" is what got me too.

**Comment by dezza** [comment]
Came here to say it also puzzled me.
