### ISSUE TITLE
Misleading message: "click anywhere to close this window" should be "close this tab"

### ISSUE THREAD

**Issue by HifeFish** [rNeomy/auto-tab-discard#235]
If all tabs of a window are discarded, a tab is opened displaying the message: 

"All tabs in this window have been discarded, click anywhere to close this window." 

This is misleading, as clicking only closes the tab, not the whole window.

**Comment by rNeomy** [comment]
Thanks!

**Comment by HifeFish** [comment]
Thanks to you for a quick fix and a very useful addon.
