### ISSUE TITLE
Translated pop-up menu options too close together

### ISSUE THREAD

**Issue by Elaborendum** [rNeomy/auto-tab-discard#238]
![image](https://user-images.githubusercontent.com/71190696/118408624-03a75600-b64c-11eb-810f-6a72097db157.png)

When the language is spanish, the "Left Tab | Close Tab | Right Tab" options are so close together it's difficult to tell they are different options at first glance.

**Comment by rNeomy** [comment]
Thanks for the report. Should get fixed by the next release.
