### ISSUE TITLE
Manual tab discard on Firefox 

### ISSUE THREAD

**Issue by ammarshahin** [rNeomy/auto-tab-discard#239]
Add a keyboard shortcut (configurable) for the common commands like manual tab discard or discard all tabs now?

**Comment by yankeexe** [comment]
@ammarshahin  You can do that with custom shortcuts for the plugins. 

More info here: https://support.mozilla.org/en-US/kb/manage-extension-shortcuts-firefox

**Comment by ammarshahin** [comment]
didn't see this option before. Thank you 😊❤
