### ISSUE TITLE
some tabs are not restored

### ISSUE THREAD

**Issue by mar04** [rNeomy/auto-tab-discard#24]
I've been using this extension since yesterday with Firefox Developer Edition, and I've noticed that sometimes some tabs fail to restore - they are empty, completely blank, with nothing in the address bar and only with a title on the tab. It happened to me at least 3 times already.

**Comment by rNeomy** [comment]
Is this happening on some particular domains? Any way to reproduce this?

**Comment by mar04** [comment]
2 times on github and once on reddit. I didn't notice any pattern or way to reproduce it, those tabs were in between a bunch of other tabs that were restored correctly.

**Comment by perdolka** [comment]
same here, on
https://support.mozilla.org/questions/
pages

**Comment by MrRobot12** [comment]
I have the same issue.

From what I've observed it seems to happen on tabs that you open in the background but don't get to before the tab unloads.

**Comment by perdolka** [comment]
@MrRobot12 
> happen on tabs that you open in the background but don't get to before the tab unloads.
Yeah! Now I can reproduce this.
Tested on random wikipedia pages, which were opened from Google search page
> in the background but don't get to before the tab unloads.

**Comment by mar04** [comment]
While that may be one trigger, I've seen it happen also to tabs that were in the foreground and were fully loaded.

**Comment by MrRobot12** [comment]
Ya. This extension is losing too many tabs to make it reliable enough to use daily.

Hopefully the developer is able to figure it out.

Are there any other addons that do the same thing and work on FF Quantum?

**Comment by perdolka** [comment]
> Are there any other addons that do the same thing and work on FF Quantum?
https://addons.mozilla.org/uk/firefox/addon/tab-unloader-we/
There's the same bug. So, I think this is a bug of new Firefox API.

**Comment by irvinm** [comment]
I've seen something like this as well.  In my case, the tabs loads with a blank page and blank URL but I can see the old tab title on the tab and if I reload the page it then goes completely blank.  (I can find the URL by searching the tab title in my history if I remember to do that before trying to refresh the page)

That is an interesting observation about the timing of opening tabs, clicking on tabs, and discarding of tabs.  I will have to try that pattern out myself.  (Although this seems like a reasonable sequence that I may have seen myself ... usually I open a tab and sometimes forget about it for a while and then when I go back it is already discarded.)

**Comment by mar04** [comment]
Thanks for the fix! So far I didn't encounter this issue in the updated version. :+1:

**Comment by derekbasch** [comment]
I was experiencing this same issue. Thanks for the fix. I will cross my fingers that it works.

**Comment by perdolka** [comment]
Unfortunately, after updating the addon to version 0.2.5, 
the problem appeared again, for some reason.

I'm sure it didn't occur in 0.2.4 (after temporary fix for #24) and appeared again in  0.2.5.

Win 10 (x64)
FF 60.0.1 (x64)
auto-tab-discard 0.2.5
TST 2.4.21

**Comment by rNeomy** [comment]
That's because the extension cache was cleared. I pushed a new update to prevent this issue. Please reopen if the issue persists after the update. Note that the already corrupted tabs are not going to be fixed.

**Comment by perdolka** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1465558
