### ISSUE TITLE
Improve the display of symbol to the discarded tabs

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [rNeomy/auto-tab-discard#242]
On Firefox Browser add-ons website I saw a complain in the reviews:
> Some tabs do not get recovered bot vanish when I click on them which is an absolute no go! Also I personally do not like the emojii or custom title prefix to mark sleeping tabs, the greyed out title was easier to recognize.

I also feel the emoji symbol looks not recognizable on certain cases. If you feel so, as my suggestion, you can add the VS15 charcters after the symbol:
💤 → 💤︎

**Comment by rNeomy** [comment]
You can optionally add any number of chars to be prepended from the options page. However, even a single char is causing issues; see https://github.com/rNeomy/auto-tab-discard/issues/257 for instance
