### ISSUE TITLE
`Permanently delete old discarded tabs if they are inactive` option not working on Brave Browser

### ISSUE THREAD

**Issue by dabat** [rNeomy/auto-tab-discard#243]
I was super excited to see the fix from #189 and all works great in Firefox.
But i have been using Brave lately, and it appears that this delete old tabs function does not seem to be working.
I have the time set to 24 hours, and i have some tabs still sitting in groups, untouched mind you, that were opened a few days ago.
Is there a way to debug this?
or please let me know if there is anything else i can do to help figure this out.
i'm currently running brave 1.25.70 on macos 11.4
thank you.

**Comment by rNeomy** [comment]
@dabat I think we just need to add `query({status: 'unloaded'})` to the observer. Please give it a try and report back

**Comment by dabat** [comment]
@rNeomy I tested this change out in Brave and Firefox, and it appears to be working as hoped!
I thought that I tried this but I cannot remember... Anyhow, thanks so much!
