### ISSUE TITLE
Addon no longer works in Chrome

### ISSUE THREAD

**Issue by wilcoxon** [rNeomy/auto-tab-discard#244]
The vast majority of tabs no longer actually discard.  I've tried turning off every "do not" option and it didn't help.  Once tabs are undiscarded, most will also no longer discard.  If I manually Discard all other tabs, it claims to work (opening the new tab saying all tabs in window are discarded) except there are still a ton of tabs no discarded.  If I manually discard current tab, it moves left but doesn't discard the tab.

Please help.  This addon is critical to my Chrome usage.  I moved here after the Great Suspender malware fiasco and it worked fine until just recently (no new extensions added between when it worked and now).

Chrome  91.0.4472.77 64-bit
auto-tab-discard 0.4.7

**Comment by wilcoxon** [comment]
I found a very weird work-around.  I installed Great-er Discarder-er.  If I discard the tab using GD and undiscard/reload the tab, then I can discard the tab using auto-tab-discard again.  There is definitely a bug here but one that doesn't make sense to me (since I think both extensions claim to use Chrome's builtin discard functionality).

**Comment by Gr8est1** [comment]
I was experiencing the same problems since updating to Chrome 91.0.4472.77 but looks like the Chrome 91.0.4472.106 update may have resolved these issues.

Since the update everything seems to be working again so hopefully whatever bugs they introduced are now resolved.

**Comment by rNeomy** [comment]
I am not able to reproduce this. Please reopen if you are still experiencing it.
