### ISSUE TITLE
Discarding consecutive tabs too quickly locks the Firefox browser

### ISSUE THREAD

**Issue by tirphana** [rNeomy/auto-tab-discard#248]
If one wants to quickly discard multiple (say 3, for example) tabs consecutively and clicks the discard keyboard shortcut, the first tab goes into some kind of mid-state until it completely discards. The issue is, if one tries discarding the second tab before this state of the first one is finished (which takes a couple of seconds on some heavier tabs), the focus jumps back to the first one which after another shortcut press just locks out the window completely, goes blank, and no other tab in that window can be accessed without restarting the browser.

After restarting, all tabs to the right of the last used tab in the affected window disappear and cannot be recovered using FF's "sessionstore" databases because this bug, I assume, corrupts those files (since they cannot be read by https://www.jeffersonscher.com/ffu/scrounger.html).

Please someone look into this, I lost important data over this stupid bug more than once already. And if anyone is working on this addon anymore and reading these issues, I would propose a suggestion of using a single keyboard shortcut for discarding a single and multiple tabs. I don't think there's a reason for them to have seperate ones, since the same key can do it depending on whether one or more tabs are selected. 

Oh, and both this bug and the previous one I reported are still present in FF 89.0.2, if it makes any difference.

**Comment by rNeomy** [comment]
> Oh, and both this bug and the previous one I reported are still present in FF 89.0.2, if it makes any difference.

I am sorry for the delay. I can only fix the bugs on my free time.
