### ISSUE TITLE
[Feature] Save and reload video timestamp on YouTube

### ISSUE THREAD

**Issue by quidnu** [rNeomy/auto-tab-discard#250]
It would be really useful to have an option to be able to restore a Youtube video to the timestamp it was at before it was discarded.

(In fact it would be useful for all media but Youtube is the biggest use case).

**Comment by friendlytherapist** [comment]
I agree, maybe use the &t thing in the url to reload it

**Comment by rNeomy** [comment]
fixed in fixed in https://github.com/rNeomy/auto-tab-discard/issues/33
