### ISSUE TITLE
URL showing as title of tab instead of actual title

### ISSUE THREAD

**Issue by MoneyAllDay** [rNeomy/auto-tab-discard#251]
If you open several tabs with "Open in new discarded tab" and "Release discarding of the next tab (tab to the right of the active tab)" is active, then the title of the tabs will be the url instead of the actual title.

Title will be corrected if those tabs are reloaded.

**Example**:
![Example](https://i.imgur.com/93nt5E3.gif)

Not sure if this can be fixed but it would be nice, specially when opening a lot of tabs this way.

Firefox 91.0.1 x64
Auto Tab Discard 0.4.7

**Comment by rNeomy** [comment]
I am not able to reproduce this on the latest version of FF. I guess it is fixed. Reopen if not.
