### ISSUE TITLE
"Do not discard when it's pinned" is not preserved in Firefox

### ISSUE THREAD

**Issue by OleksandrKvl** [rNeomy/auto-tab-discard#259]
Environment:
OS X 11.2.3, Firefox 95.0, Auto Tab Discard: 0.4.8

"Do not discard a tab when it is pinned" settings is not preserved.
Steps to reproduce: enable it, restart Firefox, check current value, it's disabled.
I have this problem even without restarting Firefox, I enable this settings but my pinned tabs are still discarded from time to time. When it happens, the corresponding value in settings always disabled.

**Comment by rNeomy** [comment]
I am not able to reproduce this on a clean profile. Can you confirm by testing the extension on a clean profile?
https://support.mozilla.org/en-US/kb/profile-manager-create-remove-switch-firefox-profiles

**Comment by OleksandrKvl** [comment]
Sorry, my bad, I've never realized there's a `Save settings` button at the bottom of the settings page. Now everything is fine, thanks :)
