### ISSUE TITLE
TST detect unload

### ISSUE THREAD

**Issue by perdolka** [rNeomy/auto-tab-discard#26]
Platform (OS): Win 10 (x64)
Version of Firefox: 59.0b12 (x64)
Version of auto-tab-discard: 0.1.8
Version of Tree Style Tab: 2.4.16

The treestyletab addon has a useful "code snippets" function - for custom rules of a tabs style .
In my opinion, the most useful function here - the marking of unloaded tabs with gray shading:
https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#change-styling-of-pending-unloaded-tabs-1363
Is it possible to add support for this thing, so that TST could detect tab unloading?
Or, it would be more correct to make changes on the TST side?

**Comment by perdolka** [comment]
UPD
Looks like RMB context menu "Do not discard this domain" also do not work with TST.

**Comment by perdolka** [comment]
Solved
Looks like it's working.

**Comment by perdolka** [comment]
Doesn't work again.
Auto Tab Discard 0.2.4
FF 60.0.1 (x64)

**Comment by rNeomy** [comment]
There is a listener for tab discarding. Basically, there is no need for a cross extension messaging. You need to report the issue to the TST developer. btw, mine works fine (injects the custom style).

**Comment by perdolka** [comment]
I'm not sure if Piroor (TST author) will take up this issue.
Is it possible to do a fix by adding checkbox: 
"**unload twice (for correct dimming of a TST-tabs)**" 
to the Options?
If you call the unload method twice (on the tab), the dimming works correctly - that's the point.
