### ISSUE TITLE
Setting explanation

### ISSUE THREAD

**Issue by friendlytherapist** [rNeomy/auto-tab-discard#265]
There is a setting that states "Minimum delay between sequential discarding checks (in seconds)3" And it is default set to 30 seconds. But when i read the explanation for point 3 it states that "The minimum acceptable value is 1 minute. The recommended value is 10 minutes." So.. who is right?

**Comment by rNeomy** [comment]
Thanks for reporting. It was an old preference that is not needed anymore. I removed its trace from the code.
