### ISSUE TITLE
Context menu item missing when extension is disabled then re-enabled

### ISSUE THREAD

**Issue by Lej77** [rNeomy/auto-tab-discard#268]
## Short description

When the addon is disabled and then later enabled the context menu items won't show up. Note that they do show up after the browser is restarted, when the addon is installed or when the settings are saved.

The issue is likely because the [`once` function in the `background.js` file](https://github.com/rNeomy/auto-tab-discard/blob/5388d50d2cfc948af4b6efcd5fd385c7c3af359c/background.js#L44-L52) isn't called when the addon is enabled.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install `Auto Tab Discard`.
 3. Disable the addon.
 4. Enable the addon again.
 5. Right click on a tab in the tab bar.

## Expected result

The context menu should include the `Auto Tab Discard` item.

## Actual result

The `Auto Tab Discard` context menu item is not there.

## Environment

 * Platform (OS): Windows 10
 * Version of Firefox: 96.0.2
 * Version of Auto Tab Discard: 0.5.0

**Comment by Chealer** [comment]
@Lej77 if this persists in the current version, could you retitle this _as an issue report_ (rather than as a task)? For example:

> Context menu item missing when extension is disabled then re-enabled

**Comment by Lej77** [comment]
I checked version Auto Tab Discard version `0.6.7` on Firefox Nightly version `130.0a1` (2024-07-20) and this issue seems to have been fixed!
