### ISSUE TITLE
Delay Loading at Browser startup?

### ISSUE THREAD

**Issue by kmand** [rNeomy/auto-tab-discard#271]
My apologies in advance, I may not quite understand if this extension can help me. I have a huge number of tabs, about 800. Chrome tries to load them all at startup, and can get into trouble. Is there a way to use the extension, to have no or few actually load until I manually select them? I want to see them in the tab bar, and use tab search to find rarely used ones, without any load that are not manually clicked on.

**Comment by rNeomy** [comment]
There is a plug-in on the options page of the extension that can help you:

`Discard all unloaded tabs on browser startup. This method discards almost all inactive tabs`

**Comment by kmand** [comment]
I value my not recently opened tabs, I want to be sure that "Discard all unloaded tabs on browser startup" doesn't actually delete them, just doesn't load them until manually clicked on after startup. Is that correct?

**Comment by rNeomy** [comment]
Your discarded tabs are safe. The only function that deletes tabs, is the trash plug-in (disabled by default). There is no other method to automatically remove/detect tabs.
