### ISSUE TITLE
Show a page when tab is discard

### ISSUE THREAD

**Issue by BTBMan** [rNeomy/auto-tab-discard#275]
hope to show a page when tab is discard, just like chrome extension `The Great Suspender`

<img width="1420" alt="图片" src="https://user-images.githubusercontent.com/26108004/154420994-9b3a875d-bc0c-4ef6-b75f-b351b57e4ac3.png">

**Comment by Technetium1** [comment]
It's best to avoid that extension, as malware/tracking was added later in development. This one is more heavily reviewed and has no tracking. You can combine it with this extension. Check `Apply Chrome's built-in memory-saving when suspending` https://github.com/gioxx/MarvellousSuspender
