### ISSUE TITLE
TST compatibility

### ISSUE THREAD

**Issue by perdolka** [rNeomy/auto-tab-discard#28]
For some reason, sometimes auto-tab-discard disappears from the TST-tabs RMB context menu.
The workaround is to disable and re-enable auto-tab-discard in about:addons and then restart FF.

**Comment by irvinm** [comment]
Thanks for the workaround @perdolka!  I wondered what happened to the menu item after I had successfully used it in the past.

**Comment by polyzen** [comment]
No need to restart Fx after re-enabling ATD, here.

**Comment by rNeomy** [comment]
I am not experiencing this. Any way to reproduce?

**Comment by polyzen** [comment]
@rNeomy, disabling and re-enabling TST reproduces this.

**Comment by polyzen** [comment]
Same thing apparently happens with the [Multiple Tab Handler addon](http://piro.sakura.ne.jp/xul/_multipletab.html.en).

**Comment by perdolka** [comment]
Fixed, thanks @Lej77
