### ISSUE TITLE
Notices at the bottom of the Options Page are difficult to read in dark mode

### ISSUE THREAD

**Issue by Elaborendum** [rNeomy/auto-tab-discard#284]
![imagen](https://user-images.githubusercontent.com/71190696/162868687-e36e907b-b4af-45fc-93b5-076c336153f3.png)

It seems like the main text color was changed according to the dark mode, but the backgrounds weren't. Leaving the notices with low contrast.

**Comment by rNeomy** [comment]
Thanks for the report. Will be fixed by the next release.
