### ISSUE TITLE
Suspended tab icon Zzz cannot be disabled

### ISSUE THREAD

**Issue by lonix1** [rNeomy/auto-tab-discard#286]
I tried the favicon "Zzz" feature, then disabled it.

Now all my suspended tabs show Zzz. Is there a way to fix that?

**Comment by rNeomy** [comment]
Use the popup interface to undiscard the discarded tabs, then discard one more time.

**Comment by rNeomy** [comment]
No I meant to use the extension's interface to _undiscard_ tabs (press the "x" button for `Discard All Other Tabs` option).
