### ISSUE TITLE
New tabs get discarded too soon

### ISSUE THREAD

**Issue by santinoscripts** [rNeomy/auto-tab-discard#288]
Maybe I'm not understanding how this addon works, so I'll explain what I expect: when a URL is loaded the tab has a timeout after which the addon discards it if the user has switched to another one and hasn't been opened since then.

This is getting on my nerves because I've reviewed every setting in case I'm missing something and this last test happened just after double clicking reset default values and closing-opening the browser, Firefox 100.

So this is what just happened. I open a webpage and leave the tab alone, am still in the same window (no alt+tab or anything), but the addon discards the tab after 3 minutes. Why? Shouldn't it wait after the number of minutes in the first value from the settings, that is defaulted to 10?
Please, explain it to me.

**Comment by santinoscripts** [comment]
BTW, now it happened after just 1 minute.

Also there's this other addon I'm using "Load background tabs lazily". Could be it's interacting with Auto Tab Discard in a wrong way?

**Comment by WHiZSTA** [comment]
i've noticed the same issue of tabs that havent been inactive for more than a min auto getting discarded. i'm not sure how it works, but it doesnt appear to be based on each tab it discards being inactive for moree than say 5min like i have configured. it appears to be if 1 tab hits that timelimit it discards all inactive tabs regardless of how long they have been inactive.

**Comment by selurvedu** [comment]
Oh boy, at first I expected it to work just like @santinoscripts described, but after using the addon for a few months and getting used to how it discards the tabs I concluded this was made on purpose. I'm happy to see I was wrong, thank you for the fix! :)

**Comment by santinoscripts** [comment]
The addon operates with the same defective behaviour as 4 months ago when I filled this bug report. At this point I'm 100% sure the dev is trolling.

**Comment by WHiZSTA** [comment]
i've since swapped to [https://chrome.google.com/webstore/detail/the-great-er-discarder-er/plpkmjcnhhnpkblimgenmdhghfgghdpp](https://chrome.google.com/webstore/detail/the-great-er-discarder-er/plpkmjcnhhnpkblimgenmdhghfgghdpp)
