### ISSUE TITLE
[Feature Request/Bug?] Don't discard tabs which are below treshold

### ISSUE THREAD

**Issue by Yannik** [rNeomy/auto-tab-discard#293]
Hi,

I have configured the extension setting `when the number of inactive tabs exceeds` to 50, but that leads to all tabs which are not matched by an exception being discarded once that treshold is reached.

This includes tabs that where just used, which is pretty annoying.

I would like that only the X oldest tabs OVER that treshold are discarded.

Am I doing something wrong, or is this just not possible?

**Comment by rNeomy** [comment]
I assume that this is related to the recently fixed bug; https://github.com/rNeomy/auto-tab-discard/issues/288

Please wait for the next release. Reopen if it is not fixed.
