### ISSUE TITLE
[Feature Request] Temporarily disable

### ISSUE THREAD

**Issue by lonix1** [rNeomy/auto-tab-discard#294]
It would be nice to have a switch that **temporarily** disables discarding.

For example, you load a bunch of tabs, and you have a poor wifi connection - e.g. you're getting on a plane, train, etc. You don't want those tabs to be discarded.

So we could click on a "temporarily disable" button, which lasts for `x` hours (configurable).

(The workaround is to disable the extension completely, which is a bad way to do it.)

**Comment by CTimmerman** [comment]
Isn't that what the "Keep tabs for this session" checkbox does in the add-on icon menu?

**Comment by lonix1** [comment]
Not really:
- that keeps the tabs for the session's duration - in my case I sometimes don't restart the browser for weeks
- I'm referring to a way to disable discarding *completely* - all tabs, all domains

**Comment by selurvedu** [comment]
@lonix1 @rNeomy TYSM! I really needed this for exactly the same use case!
