### ISSUE TITLE
Issues with FF58.0 release build \ some tabs work, others don't (v0.1.3)

### ISSUE THREAD

**Issue by irvinm** [rNeomy/auto-tab-discard#3]
Using the soon to be pushed FF58.0 (http://ftp.mozilla.org/pub/firefox/releases/58.0/win64/en-US/):

- Install FF58
- Install Auto Tab Discard, Tree Style Tab (Ease of seeing discarded tabs)
- Configure ATD to discard for any reason @ 10 seconds
- Load https://www.mozilla.org/en-US/privacy/firefox/
- Load https://add0n.com/tab-discard.html?version=0.1.3&type=install
- Load https://www.yahoo.com/
- Load https://www.newegg.com/
- Load https://github.com/rNeomy/auto-tab-discard
- See that only the first 2 suspend properly and the last 3 never suspend (auto or manual)

This could certainly be related to this build of FF58 as there is obviously been better behavior with older beta builds and with the newer FF59b2.  (Actually with my main machine upgraded to this FF58, I can't get it to work at all but I still have some investigation to do there)

**Comment by rNeomy** [comment]
As I have already mentioned, there is nothing we can do when an internal API is not functioning properly. We just need to wait until Firefox fixes the API. This works fine in the Chrome version which means the extension is triggering the discard API but it is not functioning.

**Comment by irvinm** [comment]
Everything works fine in FF59b3.  (TST, LP [+binary], ATD)  Closing.
