### ISSUE TITLE
What is the difference with "Tab Unloader"?

### ISSUE THREAD

**Issue by gagarine** [rNeomy/auto-tab-discard#30]
What is the difference with https://addons.mozilla.org/en-US/firefox/addon/tab-unloader-we/ ?

**Comment by gagarine** [comment]
So, I tested both and I think Tab Unload is better in term of UX and they both use the native API for tab unload. Perhaps I'm missing something.

**Comment by motin** [comment]
I was wondering the same. So far I have seen the following differences, which made me choose Auto Tab Discard over Tab Unloader: 
* Tab Unloader is only for Firefox. Auto Tab Discard has a Chrome version too
* Auto Tab Discard has a great approach to issue reporting, feature requests and access to source code (Github)

**Comment by perdolka** [comment]
Also
- Tab Unloader WE - doesn't updated over 5 months.
- Tab Unloader WE - still haven't fixed the same bug https://github.com/rNeomy/auto-tab-discard/issues/24

**I think this issue can be closed.**

**Comment by TroudhuK** [comment]
> Tab Unloader is only for Firefox. Auto Tab Discard has a Chrome version too

Good point for Tab Unloader, you shouldn't encourage the Google's (big)browser.

**Comment by gagarine** [comment]
Now with have https://addons.mozilla.org/en-US/firefox/addon/dormancy/ also...

**Comment by fermulator** [comment]
I think the readme decently (already) states the value-add:
https://github.com/rNeomy/auto-tab-discard/blob/master/README.md
> This extension is more efficient and should be less buggy compared to the alternatives extensions that use DOM replacement method.

**Comment by grahamperrin** [comment]
+1 to closing this issue. 

For me the most significant difference is that Tab Unloader does not have a support site.
