### ISSUE TITLE
Unloading the only active tab in a window

### ISSUE THREAD

**Issue by SeanMcMillan** [rNeomy/auto-tab-discard#301]
It used to be that if you used "Discard All other tabs" that it would still leave the active tab in each window loaded.

Now it seems to open a new tab that's (mostly) blank. And it's nice that that tab closes itself if you click on it, but now all of my windows are called "New Tab". And which adjacent tab gets focus seems unreliable. It's not always the one I was on. (Though this may be because of an interaction with my session manager.)

Can we get a setting to not discard the active tab in a background window, please?

**Comment by rNeomy** [comment]
Have you tried unchecking the `Open a temporary blank page when all tabs in an inactive window are discarded (to be able to discard the active tab on this window)` plugin?

**Comment by rNeomy** [comment]
There will be two improvements:

1. Open the blank page in the place of the active tab to make sure the old active one gets focused when this tab is closed.
2. Use the title and favicon of the active tab for the blank page.

**Comment by SeanMcMillan** [comment]
> Have you tried unchecking the `Open a temporary blank page when all tabs in an inactive window are discarded (to be able to discard the active tab on this window)` plugin?

I swear I looked at every setting and didn't see it. I don't know what's wrong with my brain.
