### ISSUE TITLE
How does the positive list ("whitelist") work?

### ISSUE THREAD

**Issue by danielmmmm** [rNeomy/auto-tab-discard#305]
I installed ATD in Firefox 104.0 and it seemed to work as intended, suspending inactive tabs. Since there are only few webpages that use an extreme amount of memory (>300 MB), I thought it a good idea to only suspend these particular tabs. I added "finn.no" (without the quotation marks) to "Only discard the following inactive hostnames...". And suddenly, ATD stopped suspending tabs! To be on the safe side, I also tried "re:finn.no", "re:finn", and "www.finn.no". These didn't work either.
I activated "Display logs", but didn't see anything in the console. In about:config, "browser.tabs.unloadOnLowMemory" was already set to false.
I also noticed that the ATD icon turned blue for some tabs, even though they weren't in the positive list. Having "finn.no" in the positive list made ATD report that e.g. youtube.com and github.com where on the "whitelist".

Did I miss something here? Did I use a wrong hostname?

**Comment by rNeomy** [comment]
For me, if I add "www.finn.no" to the list, it gets discarded after the specified time. The other HTTP pages will display the blue icon since they don't get discarded for not being in the list.

**Comment by danielmmmm** [comment]
Thanks for your reply!
I tried it again, with "www.finn.no, www.youtube.com" in FF v105.0b7. It seems to be working as expected 😊
Maybe an earlier version of FF screwed up? I am on the beta update channel ...
