### ISSUE TITLE
[Request] Close all discarded tabs in window

### ISSUE THREAD

**Issue by amplifythought** [rNeomy/auto-tab-discard#309]
I tend to have a lot of tabs/windows open at all times, so this plugin has been a lifesaver. Occasionally while I research something I might have a window open with several tabs and forget to close some tabs as I move from link to link. Eventually I will realize I have several tabs open I don't need at all anymore, and of course they've been discarded. It would be nice to be able to close every discarded tab in a window.

**Comment by Mickael-Martin** [comment]
Hello,

You can trash tabs if you want. You must enable trash option.

**Comment by amplifythought** [comment]
Found it, thank you! Sorry about that, I just missed that.
