### ISSUE TITLE
Tabs often discarding almost immediately despite settings

### ISSUE THREAD

**Issue by LucasD3** [rNeomy/auto-tab-discard#313]
I have set tabs to discard after 4 minutes, and I have enabled both "Discard all unpinned tabs on a browser or extension startup" and "Discard all pinned tabs on a browser or extension startup". Strangely, while using the browser, often (or perhaps most of the time, but certainly not always), tabs discard within a few seconds after leaving them. Sometimes this occurs when I had created the tab less than a minute ago -- in other words, the tab has existed for less than 4 minutes. Is this a known issue? Could it be that the extension is restarting and thus discarding all tabs due to setting?

**Comment by immortaliseORdie** [comment]
Hey, have you found a solution for this?
