### ISSUE TITLE
Keep this tab for this session, doesn't work

### ISSUE THREAD

**Issue by heywolf15** [rNeomy/auto-tab-discard#317]
Windows 10, Firefox 106.0

Keep this tab for this session function doesn't work after update 0.6.4

**Comment by heywolf15** [comment]
I think this is related to Firefox 106. Trying to downgrade the extension to 0.6.3, the checkbox will still be checked if the tab being open and will uncheck for a moment after changing the tab. On 0.6.4, checking the box will immediately uncheck after re-open context menu

**Comment by mgalvey** [comment]
I am seeing the same behavior in FF 105.0.2 on Fedora and 0.6.4 of the extension. The "keep tabs with paused media" setting also appears to be broken, but I actually first discovered and enabled it while I was troubleshooting this issue, so I don't have a previous working state to compare against.

**Comment by mkbloke** [comment]
I'm also seeing this with Firefox 106 on Linux Mint and Auto Tab Discard 0.6.4.  If it helps, this is what is shown in the developer console upon ticking "Keep This Tab For This Session":
```
Uncaught Error: Type error for parameter updateProperties (Unexpected property "autoDiscardable") for tabs.update.
    <anonymous> moz-extension://823a220e-0513-49dc-bdb1-e644ba647632/data/popup/index.mjs:14
    EventListener.handleEvent* moz-extension://823a220e-0513-49dc-bdb1-e644ba647632/data/popup/index.mjs:14
5 [index.mjs:14:54](moz-extension://823a220e-0513-49dc-bdb1-e644ba647632/data/popup/index.mjs)
    makeError resource://gre/modules/Schemas.jsm:550
    throwError resource://gre/modules/Schemas.jsm:2669
    fixedArgs resource://gre/modules/Schemas.jsm:2737
    map self-hosted:221
    checkParameters resource://gre/modules/Schemas.jsm:2730
    stub resource://gre/modules/Schemas.jsm:2840
    <anonymous> moz-extension://823a220e-0513-49dc-bdb1-e644ba647632/data/popup/index.mjs:14
    (Async: EventListener.handleEvent)
    <anonymous> moz-extension://823a220e-0513-49dc-bdb1-e644ba647632/data/popup/index.mjs:14
```
