### ISSUE TITLE
"Keep This Tab for This Session" No Longer Working

### ISSUE THREAD

**Issue by Gathouria** [rNeomy/auto-tab-discard#321]
realized this about 2-3 days ago, but when tabs are marked to not be discarded the checkbox will either immediately or very quickly uncheck the box again.

Been using this add-on for maybe 2 or more years on Firefox without any issue, so this is something new. Seemed to be happening before updating to the latest Firefox version, but also still happens after updating to it (Firefox 106.0.1). There aren't very many loaded tabs running right now, so I doubt it's a cap on the number of unloaded.

**Comment by rNeomy** [comment]
Hi, it is fixed on 0.6.5 release. Please wait for AMO to accept the version;
https://github.com/rNeomy/auto-tab-discard/issues/317
