### ISSUE TITLE
[Request] right click submenu

### ISSUE THREAD

**Issue by behhNa** [rNeomy/auto-tab-discard#324]
Hi,

since one of the last updates the "Keep This Tab for This Session" is in an even deeper submenu (right click > Auto Tab Discard > Keep Tabs > Keep This Tab for This Session).
Is there a way to shorten that again (or even more)? There is a lot mouse movement involved.

Anyways. 
Thanks for the addon. It's a must-have and don't want to miss it anymore!

**Comment by rNeomy** [comment]
Unfortunately, we can only have six context menu items on the top menu. If you use the main popup interface, you have access to all the items with two clicks.

**Comment by behhNa** [comment]
I didn't know that there is a restriction. I'll use your suggestion now.
Thank you
