### ISSUE TITLE
Saving youtube timestamp on firefox not working

### ISSUE THREAD

**Issue by thomasfulton** [rNeomy/auto-tab-discard#326]
On Macos 12.6, firefox 106.0.3. When it discards youtube tabs it doesn't save the timestamp and starts the video again from the beginning. Even youtube's built-in video progress saver doesn't work

**Comment by gitdine** [comment]
Yep same since 0.6.5 update. Not having this feature is very annoying, please fix.
And I don't want to whitelist YT because the site is a massive memory hog.

**Comment by thomasfulton** [comment]
It wouldn't be so bad if the tab discard didn't also sometimes prevent youtube's native play position save from working

**Comment by rNeomy** [comment]
Thanks for the report. Will get fixed by 0.6.6 release.

**Comment by thomasfulton** [comment]
This works great, thanks!
