### ISSUE TITLE
[Feature request] Save time of media pages

### ISSUE THREAD

**Issue by Diddern** [rNeomy/auto-tab-discard#33]
First off; great plugin! 

When pausing ie. a Youtube-video the tab sometimes gets discarded as it should, but when reactivating the tab, it would be nice to start the video from the time it was paused, and not a fresh reload of the page.

**Comment by rNeomy** [comment]
certainly doable. Though it needs interaction with YouTube APIs. Anybody interested in working on this?

**Comment by surajmandalcell** [comment]
For some insane reason (for me) the video resumes from where it was left accurately  :open_mouth:  .
Using Firefox 60.0b7 beta

**Comment by AtomicBones** [comment]
YouTube appears to do this automatically anyway, at least it does for me. I.e. listening to an hour long mix, close FF and reload and it continues playing where it left off. Just like Netflix would.
Either-way reading the variables should be simple to grab Position and Restore that regardless of video sites (Although the Variables from JS would be different per video site)

I'm worried this extremely important plugin has been abandoned at this point. If so I'll attempt to carry on with the Development work although I rarely have the free time for this so I hope either @Diddern  or @rNeomy can work on this. RegEx can probably grab the variable from every known Streaming Site and this can easily be restored with a JavaScript Injection by the Addon.

**Comment by surajmandalcell** [comment]
@AtomicBones the plugin does what it should do without any problems. If any issues/bug appears i guess then only any attention is needed.

**Comment by trlkly** [comment]
YouTube does attempt to restore to a point close to where you were, but it isn't exact, and it often doesn't work at all and you lose everything. 

I would not think this would need a special variable for various sites. Just detect the video element, and then check the [currentTime](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/currentTime) element. Just set a timer to save the position every few seconds. Or the timer could check the [paused](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/paused) and [ended](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/ended) property and only save the currentTime if those are true and false, respectively. Also maybe check whether the tab is visible, and only bother running the timer if it is not. 

Of course, having a per-tab "don't discard" optino would be great, too. The Great Discarder addon has that.

**Comment by 3j9fkyahunqoxwqu** [comment]
Hello

Also there is an addon for this:
https://github.com/nkestrel/mediaurltimestamper

**Comment by Jaweiwei** [comment]
> Hello
> 
> Also there is an addon for this:
> https://github.com/nkestrel/mediaurltimestamper

This addon isn't for Chrome. Do you know of one that works for chrome? Though I would rather the feature be built into auto tab discard just for the sake of only needing one addon/extension.

**Comment by rNeomy** [comment]
We are going to have a plug-in to save the YouTube's timestamp just before discarding on 0.5.0 release. It is disabled by default.
