### ISSUE TITLE
[Feature request] Missing functionalities from tab suspender

### ISSUE THREAD

**Issue by JosephCaillet** [rNeomy/auto-tab-discard#35]
On tab suspender, there was an option in context menu to have access to suspend tabs actions. I miss it in auto tab discard :(
An other option I liked was the option to display placeholder page, which needed a click to reload the tab. I usually have a lot of tab, and navigate through them using ctrl+tab. With tab suspender, suspended tabs were not reloaded, and now with auto tab discard they are, which is pretty annoying for me.

Is there a way to implement these features ?
Thanks

**Comment by TroudhuK** [comment]
One other useful feature I used: alt+click on a tab to suspend it.

**Comment by rNeomy** [comment]
> On tab suspender, there was an option in context menu to have access to suspend tabs actions. I miss it in auto tab discard :(

The context menu is moved to the tab's context which fits better in my opinion
![screen shot](https://user-images.githubusercontent.com/14104614/37861713-5a5c8834-2f37-11e8-8971-d6f60589cf51.png)

> An other option I liked was the option to display placeholder page

ATD uses internal browser's API to perform discarding (this is way more efficient method compared to the method I used in the Tab Suspender extension). It is not doable unless it gets implemented by browsers. 

> One other useful feature I used: alt+click on a tab to suspend it.

Unfortunately not possible either. There is no API for that!

**Comment by JosephCaillet** [comment]
> The context menu is moved to the tab's context which fits better in my opinion

I prefer it to be in the context menu, because I can open it anywhere on the page, and when I am on the go using a touchpad, I can just right click or use the context menu key, instead of having to move the mouse cursor.

> ATD uses internal browser's API to perform discarding (this is way more efficient method compared to the method I used in the Tab Suspender extension). It is not doable unless it gets implemented by browsers.

Ok, I understand. (Even if I did not found the new method really more efficient: using 42 tabs, I only saw a difference between 100 and 300 Mo, and I have 8 Go of RAM)

**Comment by rNeomy** [comment]
@JosephCaillet we will have optional page context option as of the next release which is disabled by default.

> Ok, I understand. (Even if I did not found the new method really more efficient...

Memory usage is not the only concern here. Session restoring and bookmarking issues we had with the old extension are also solved in the native method.
