### ISSUE TITLE
Disable notifications

### ISSUE THREAD

**Issue by esa1975** [rNeomy/auto-tab-discard#350]
Hello. Thank you for the excellent add-on. Is there a way to disable notifications? I don't need to know that I set the option to keep a tab because I just took the action myself. Notifications are generally only useful when something happens that you didn't initiate yourself. If there is an existing setting, I can't seem to find it.

**Comment by bs27975** [comment]
If the above comment indicates that notifications have been turned off, it has not proven effective for me. Have they been?

A 'quick fix' might be to have in the Options or FAQ page a description of how to turn the Notification permission off.

On Win 10 Firefox 128.7.0esr (64-bit), extension version 0.6.7
