### ISSUE TITLE
[Feature request] Keep most recent tabs loaded

### ISSUE THREAD

**Issue by robbely** [rNeomy/auto-tab-discard#356]
In a previous xul addon - "Auto Unload Tab" it was possible to set a number of recent tabs that would remain open - eg if it was 10 and the timer was set to 10 mins, the 10 most recently visited tabs would remain loaded after the 10 mins. If an 11th was created/reloaded - the oldest of the 10 would then be subject to unloading.

Could this feature be added to auto-tab-discard?

**Comment by rNeomy** [comment]
It is similar to the first option that we have. Please take a look at the options page.

**Comment by robbely** [comment]
This isn't the same - the first option will discard ALL tabs when a limit is reached, I'm looking for the option to always keep a fixed number of tabs opent

**Comment by rNeomy** [comment]
No, this option means the extension checks all not-discarded tabs every x minutes and if the number exceeds the provided value, it will discard the oldest ones.

**Comment by rNeomy** [comment]
It is not going to remove discarding of a discarded tab if for instance you are closing a not-discarded tab though.

**Comment by robbely** [comment]
> No, this option means the extension checks all not-discarded tabs every x minutes and if the number exceeds the provided value, it will discard the oldest ones.

I have the settings set to 10 tabs allowed and 10 mins interval. I just opened 11 tabs and waited 10 mins and all but the currently open tab was discarded - perhaps this is a bug?
