### ISSUE TITLE
Closing tab releases adjacent discarded tab

### ISSUE THREAD

**Issue by lugoazul** [rNeomy/auto-tab-discard#357]
Hi.
When I close a tab between discarded tabs, it will focus on the adjacent tab releasing it from its discarded state.
This behavior is very annoying and inconvenient. Am I missing some option in settings to avoid this...?
Thanks.

**Comment by rNeomy** [comment]
This is the browser's default behavior. This extension supports closing a tab from the popup interface as well as a shortcut key. If you use those, it will switch to the nearest not-discarded tab instead.
