### ISSUE TITLE
[Feature request] Blacklist instead of whitelist options

### ISSUE THREAD

**Issue by edwardgalligan** [rNeomy/auto-tab-discard#36]
Currently, the entire set of options in this extension are what I would describe as "whitelist-oriented". What I mean by this is, the extension is designed so that you can:

- auto-discard all tabs
- set some options to whitelist some tabs so they are not discarded (e.g. set domain "Exceptions" or avoid discarding tabs opened less than 600 seconds ago, or avoid discarding pinned tabs)

What would be very nice is the opposite of this:

- don't auto-discard any tabs
- set some options to always auto-discard some very resource-intensive domains after a set period of inactivity

**Comment by rNeomy** [comment]
Thanks for the suggestion. We will have a new operation mode in the options page as of the next release.
