### ISSUE TITLE
[Feature Request] Add Option to Not Discard Tabs With Permission to Send Notifications

### ISSUE THREAD

**Issue by lukasubo** [rNeomy/auto-tab-discard#37]
I find that my entire whitelist is made up of domains that are allowed to send me notifications (Gmail, Slack, etc.). It would be a good feature to have an option to automatically whitelist any domain which has permission to send notifications.

Really great addon, by the way. It prevents Firefox from absolutely crippling my laptop.

**Comment by rNeomy** [comment]
Thanks for the suggestion. We will have this in the next release.
