### ISSUE TITLE
Shortcut keys

### ISSUE THREAD

**Issue by guraltsev** [rNeomy/auto-tab-discard#38]
Could you add a keyboard shortcut (configurable) for the common commands? Like ctrl+something?

Also could shift+click on the tab in the tabbar suspend the tab?

**Comment by rNeomy** [comment]
![screen shot](https://user-images.githubusercontent.com/14104614/37861242-781bd4c4-2f2d-11e8-8bff-6bfd9243ec82.png)

**Comment by rNeomy** [comment]
In Firefox still, it is not possible to assign custom shortcuts as far as I know. Also finding empty keyboard combinations is pretty hard! In Chrome, you can now use chrome://extensions/shortcuts to assign the shortcuts.


> Also could shift+click on the tab in the tabbar suspend the tab?

Unfortunately not, there is no API for that.

**Comment by ammarshahin** [comment]
it's 2021 now! still no progress on the shortcuts ?!

**Comment by rodrigodc** [comment]
See chrome://extensions/shortcuts
