### ISSUE TITLE
Quicker commands

### ISSUE THREAD

**Issue by rayman89** [rNeomy/auto-tab-discard#4]
Could you add to tab and/or page context the "whitelist this page" and "whitelist this domain" to quickly add pages to the whitelist please and also include the unload this tab/other tabs to the context menus as well? Thank you.

**Comment by rNeomy** [comment]
we already have "Do not discard this domain" in the tabs context menu. There is no support for "whitelist this page" at the moment. Do we need "Do not discard this URL" too?

![screen shot 2018-01-24 at 10 22 59 am 2](https://user-images.githubusercontent.com/14104614/35318509-eb7b659e-00f0-11e8-837b-16333fee2d83.png)

> include the unload this tab/other tabs to the context menus as well

We already have these too.

**Comment by rayman89** [comment]
Would be cool before I used to protect the tab and the unload addons would not discard protected tabs but now there is no such thing so It would be nice to have it. Or if you prefer you could put an on off switch on the do not discard this domain that would work as well.

**Comment by rNeomy** [comment]
I just checked on FF59 Windows version and menu appears just fine;
![screen shot 2018-02-08 at 11 54 52 am](https://user-images.githubusercontent.com/14104614/35962589-e31c38a0-0ca9-11e8-8050-e156ce926604.png)

**Comment by rayman89** [comment]
Uninstalling the addon restarting firefox and starting it again made the menu appear.
