### ISSUE TITLE
[Feature Request] Mix the timer-based and number-based Discard options

### ISSUE THREAD

**Issue by Luklek** [rNeomy/auto-tab-discard#45]
I would like to discard Tabs when their number exceed X, but only start discarding the extra Tabs after they have been inactive for Y time.
Thanks

**Comment by rNeomy** [comment]
Finally got the chance to fix this; https://github.com/rNeomy/auto-tab-discard/commit/410d5541af7f3f464fccc4be36ab4667d9f91ff5

Still not tested on FF. Chrome version works as expected.

**Comment by rNeomy** [comment]
![screen shot 2018-05-22 at 8 51 54 pm](https://user-images.githubusercontent.com/14104614/40375828-459971f4-5ddc-11e8-8eb0-761b2a326328.png)

**Comment by rNeomy** [comment]
@eavrunin true. Thanks for the report. Fixed on 0.2.8

**Comment by eavrunin** [comment]
That did it.  Thanks!
