### ISSUE TITLE
Temporary add a tab to the black/white list until close that tab

### ISSUE THREAD

**Issue by Gnustier** [rNeomy/auto-tab-discard#47]
Temporary add a tab to the black/white list until close that tab

Could you please, 
Make ability to temporary add a tab to the black or white list, and remove it from the list after close that tab ?

**Comment by rNeomy** [comment]
There is a new item to prevent discarding (temporarily) in the toolbar's popup. Have you tried that?

**Comment by Gnustier** [comment]
Yes, there is a feature which name is "do not discard for now (session only)". 
I hide the icon from toolbar and that's why i didn't notice that.

Could you make another similar feature that not discarding a tab until close that tab, and make these two features mutual exclusion ?

**Comment by rNeomy** [comment]
As of the next release, this option works per the tab, not per the page. Unfortunately, Firefox does not support this yet.

It means when the option is checked, even if this extension gets reloaded or the page URL is changed, still the value persists.
