### ISSUE TITLE
FF58.0 \ v0.1.3:  Incompatibilty with LastPass addon

### ISSUE THREAD

**Issue by irvinm** [rNeomy/auto-tab-discard#5]
As mentioned in https://github.com/rNeomy/auto-tab-discard/issues/3, I couldn't get Auto Tab Discard to work at all with my main Firefox profile with a total of 28 addons.  

I spent time disabling all of my addons and slowly re-enabled them till it stopped working.  At the end of the day, the conflicting addon was LastPass v4.2.3.20 & v4.2.4a (https://addons.mozilla.org/en-US/firefox/addon/lastpass-password-manager/).  [I do have the binary component installed as well - https://lastpass.com/download/cdn/lastpass_x64.exe]

When LastPass is enabled, I could not get Auto Tab Discard to work at all.  When disabled (27 other addons enabled), I replicated the behavior described in https://github.com/rNeomy/auto-tab-discard/issues/3.

**Comment by rNeomy** [comment]
> When LastPass is enabled, I could not get Auto Tab Discard to work at all

Even on FF 59?

**Comment by irvinm** [comment]
I'll give it a try in FF 59.

**Comment by irvinm** [comment]
Everything works fine in FF59b3.  (TST, LP [+binary], ATD)  Closing.
