### ISSUE TITLE
Blacklist feature doesn't work

### ISSUE THREAD

**Issue by edwardgalligan** [rNeomy/auto-tab-discard#51]
Firstly, thank you so much for taking on my feature request in #36; it's really encouraging to see such a prompt and open response.

However, sadly, after upgrading, it doesn't seem to work 😕

I've tried the following quick test:

![screen shot 2018-05-23 at 13 32 04](https://user-images.githubusercontent.com/170268/40424510-b8f8b090-5e8d-11e8-8cfd-ddb0dfc7820d.png)

and also tried the same with various variations on the above like:

```
re:slack
```

```
slack.com
```

```
myorganisation.slack.com
```

All of the above tests just result in every single tab being auto-discarded.

**Comment by rNeomy** [comment]
I just pushed a new version. Please reopen if the bug persists.
