### ISSUE TITLE
Tabs not discarded when e10s is disabled

### ISSUE THREAD

**Issue by r-a-y** [rNeomy/auto-tab-discard#52]
Thanks for writing this important addon!

I'm encountering an issue where tabs are not discarded when e10s is disabled.  You can disable e10s by setting `browser.tabs.remote.autostart` and `browser.tabs.remote.autostart.2` to `false` in about:config.

Hopefully, it is an easy fix, but I understand if it isn't.

Here's the debug log:

```
[Exception... "Component returned failure code: 0xc1f30001 (NS_ERROR_NOT_INITIALIZED) [nsIMessageSender.sendAsyncMessage]"  nsresult: "0xc1f30001 (NS_ERROR_NOT_INITIALIZED)"  location: "JS frame :: resource://gre/modules/ExtensionUtils.jsm :: sendAsyncMessage :: line 533"  data: no]  (unknown)
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  menu.js:162
Unchecked lastError value: Error: Script '<anonymous code>' result is non-structured-clonable data  background.js:105
```

Update - Looks like Firefox devs says the discard API only works for e10s:
https://bugzilla.mozilla.org/show_bug.cgi?id=1442924

**Comment by rNeomy** [comment]
Unfortunately, there is no workaround for this. Tab discarding is an internal API.

**Comment by r-a-y** [comment]
Yeah, I saw the Bugzilla ticket.  Going to close this one out.
