### ISSUE TITLE
Unloaded tab favicons are just a white box with privacy.resistFingerprinting on

### ISSUE THREAD

**Issue by casw9413** [rNeomy/auto-tab-discard#55]
When the option in about:config "privacy.resistFingerprinting" is enabled the tab favicon turns into a white box:

setting ON:
https://my.mixtape.moe/bddlrw.png

setting OFF:
https://my.mixtape.moe/fetntk.png

This seems to be caused by this "bug":
https://bugzilla.mozilla.org/show_bug.cgi?format=default&id=1452391

Which looks like it won't be fixed. 

Is there anyway to make it so the discard tab favicon doesn't change or a way to whitelist the discard tab add-on so the changed favicon is allowed?

**Comment by rNeomy** [comment]
I am not able to reproduce this. Anyways, we are going to have a new option "change favicon of discarded tabs" in the options page. If the problem persists, uncheck this option.

**Comment by casw9413** [comment]
Hmm, I'm not able to as well. It seems like maybe Mozilla pushed an update to fix it? Thanks for the alternative fix!
