### ISSUE TITLE
Firefox v61.0 - Tabs not discarding

### ISSUE THREAD

**Issue by voidox** [rNeomy/auto-tab-discard#56]
Firefox updated to version 61.0 (stable release) and I have just noticed that my tabs are no longer being discarded as they were before the update to this version.

What is happening is that when I right click -> force discard tab, the tab focus changes to another tab, as usual, but the tab itself does not discard. To confirm this, simple example, when I try to force discard a tab that has a YouTube video playing: the tab focus changes but the video continues to play. The webpage is not discarded and does not load/re-load when you click back on it. 

The tab name and icon does fade/circle shows, but when I click on a discarded tab, there is no page load, the webpages are just there as if I didn't have the add-on. As for auto discarding, again, the tab name/icon does change as per the timing rules set, but the webpage itself isn't being discarded. 

Now just to check, I installed a few other tab discard/unloader add-ons and none of them seem to work either. Now some of those haven't been updated in a while, but I think FF 61.0 might have done something to affect tab discarding.

**Comment by casw9413** [comment]
This is probably because of the new feature "Tab Warming" that was introduced in FF61

https://www.ghacks.net/2018/01/12/firefox-tab-warming-explained/

**Comment by perdolka** [comment]
@casw9413 
Thus, if I switch the 
`browser.tabs.remote.warmup.enabled` 
to the **false**, auto-tab-discard will works again?

**Comment by voidox** [comment]
hm, I've already disabled the tab warming featur... tab discard still doesn't work.

**Comment by casw9413** [comment]
@perdolka @voidox  Then I'm not sure. It's working for me on FF61 even with the Tab Warming enabled. So my guess was wrong, sorry.

**Comment by voidox** [comment]
@casw9413 ah, good to hear that its working for u on FF61... means its something on my end probably. I posted cause I was worried FF61 might've broken the extension.

**Comment by voidox** [comment]
So just for an update, I tried a few things but what fixed this for me was to create a new Firefox profile. You might also try a "refresh Firefox" before that. But ya, working fine now :)
