### ISSUE TITLE
[Suggestion] White icon

### ISSUE THREAD

**Issue by happysurf** [rNeomy/auto-tab-discard#6]
Please provide a white toolbar icon for dark personas skins.
Thanks.

**Comment by rNeomy** [comment]
Thanks for the report. Here is how it looks in both FF and Chrome after the recent commit.

![screen shot 2018-01-24 at 11 38 17 am](https://user-images.githubusercontent.com/14104614/35321181-b2a5ffc6-00fb-11e8-9507-b077caf233de.png)

**Comment by happysurf** [comment]
Your test is done with Mozilla black theme, but if you use a dark personas skin like this https://addons.mozilla.org/en-US/firefox/addon/aparker-s-space-theme/ all the Firefox toolbar icons are inverted in pure white, not gray.

**Comment by rNeomy** [comment]
so do we prefer white over the gray color that is used in the default black theme? I would say this gray is more eye friendly

**Comment by happysurf** [comment]
With the default black theme you are right, but with dark personas all the icons are white:

![personas](https://user-images.githubusercontent.com/13637587/35322696-6ea2d886-00eb-11e8-8437-ed1f7520ba2f.png)
For that you must provide a black, gray and white icon.

**Comment by rNeomy** [comment]
There is no manifest entry for that. We need to select an icon set for the light theme. Either the complete white or the current gray.

**Comment by happysurf** [comment]
Complete white is perfect I think.

**Comment by rNeomy** [comment]
white it is
