### ISSUE TITLE
Whitelist from context menu

### ISSUE THREAD

**Issue by rayman89** [rNeomy/auto-tab-discard#60]
Could you add a "do not unload this tab" (as in that particular tab no matter what url it has) and a "never unload this domain" or something like that to the context menu to quickly add it to the whitelist when auto unload is enabled?

**Comment by rNeomy** [comment]
We have these options in the popup. So you want duplicates in the context-menu too?

**Comment by rayman89** [comment]
Yes please. You could add it as an option so that people who do not want this feature can turn it off so nobody looses.

**Comment by rNeomy** [comment]
We will have this as of the next release. Make sure to enable the "page" context in the options page as it is disabled by default.

**Comment by allanlaal** [comment]
whens the next release? right now this is missing still
