### ISSUE TITLE
Auto Tab Discard clutters up Browser Console with spurious errors

### ISSUE THREAD

**Issue by ssokolow** [rNeomy/auto-tab-discard#63]
I'm trying to clear up my browser console so that it's less of a bother to diagnose actual problems and I've noticed that Auto Tab Discard is periodically producing this error:

    Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.

It lists the source as `background.js:155` which corresponds to this bit of code:

```js
  const echo = ({id}) => new Promise(resolve => chrome.tabs.sendMessage(id, {
    method: 'introduce'
  }, resolve));
```

If you were using `browser.tabs.sendMessage`, the proper way to silence it would be to add a `.catch` to the promise it returns. I don't have direct experience with the old Chrome-style API, but a quick look at Firefox's source on DXR [[1]](https://dxr.mozilla.org/mozilla-central/source/toolkit/components/extensions/ExtensionCommon.jsm#648) [[2]](https://dxr.mozilla.org/mozilla-central/source/toolkit/components/extensions/ExtensionCommon.jsm#576) suggests that all you need to do in order to silence that message is read from the `chrome.runtime.lastError` property, even if you don't do anything with what you read.

**Comment by rNeomy** [comment]
Thanks for the report. It should be fixed.
