### ISSUE TITLE
notworking if multiprocessor support is off

### ISSUE THREAD

**Issue by linvinus** [rNeomy/auto-tab-discard#66]
i'm not shure is this a bug or just firefox limitation.
but if in about:config `browser.tabs.remote.autostart=false` then tabs do not discarding.
ff62 linux.

**Comment by rNeomy** [comment]
mine works fine on a Mac. Have you tried on a clean profile with just ATD extension installed?

**Comment by linvinus** [comment]
Thanks for reply, yes i try clean profile and FF from FF site, not from my distribution.
After click on menu item "Discard all inactive tabs" , tabs in tab bar looks absolutely the same as when  browser.tabs.remote.autostart=true, but if you click on any "discarded" tab you will get content immediately, instead of loading from cache.
And after that, the tab in tab bar do not change it state, i mean it steel look like discarded.

by the way,  option change browser.tabs.remote.autostart will make effect only after FF restart.

there is example, wikipedia was "discarded" then restored
![2018-09-30 19-37-31](https://user-images.githubusercontent.com/1043873/46259938-8ce3db80-c4e8-11e8-8fd5-bcd607646a7e.png)

**Comment by rNeomy** [comment]
Right, I forgot to test after a restart. Seems like this is a bug; https://bugzilla.mozilla.org/show_bug.cgi?id=1442924

> This disables e10s.  discard only works with e10s enabled.

Based on the replies, there is no plan to fix this.

**Comment by linvinus** [comment]
thanks for the answer!
probably should be in FAQ.

**Comment by rNeomy** [comment]
We now have a new FAQ referencing this thread.

**Comment by rNeomy** [comment]
https://add0n.com/tab-discard.html#faq8

**Comment by 3j9fkyahunqoxwqu** [comment]
Hello
Thanks for this great addon
Is this means that addon won't work on android?
