### ISSUE TITLE
Option to disable menu item "Open Discarded Link in New Tab"

### ISSUE THREAD

**Issue by kernc** [rNeomy/auto-tab-discard#67]
[Recently](https://github.com/rNeomy/auto-tab-discard/commit/2d337f532c49c7a92b19ff27924819827c3b48d8), the wonderful add-on acquired a new right-click context menu item (_Open Discarded Link in New Tab_).

Please make the menu item configurable (i.e. option to disable).

**Comment by Keith94** [comment]
Should also rename it to _"Open Link in New Discarded Tab"_ imo.

**Comment by rNeomy** [comment]
Thanks for the report. Will be fixed on the next release.
