### ISSUE TITLE
[feature request] focus active tab if close a tab next to discarded tab

### ISSUE THREAD

**Issue by mozartilize** [rNeomy/auto-tab-discard#68]
If I close a tab which is next to a discarded tab, the discarded tab will be reloaded.
How about the extension find another active tab and focus to it, if not, a new tab can be opened?

**Comment by rNeomy** [comment]
Use the close button in the popup and it will take care of focusing the closest active tab. If you are on Chrome, you can assign a keyboard shortcut as well.
