### ISSUE TITLE
Suggestion: allow discarding a specific tab (ignoring whitelist)

### ISSUE THREAD

**Issue by isiahmeadows** [rNeomy/auto-tab-discard#7]
Basically, it'd be nice to force-discard a particular tab (e.g. Pandora) even when it's whitelisted. In case you're wondering, I made extensive use of [The Great Suspender](https://chrome.google.com/webstore/detail/the-great-suspender/klbibkeccnjlkjkiokjodocebajanakg?hl=en), which had an option to suspend the current tab without regard to the whitelist. (Another benefit it had was maintaining suspension *after* browser close/reopen, but that's not something I feel is an absolute must, as I hardly used it save for keeping open a largish PDF file that I wasn't actively reading until later.)

**Comment by rayman89** [comment]
I agree but only when selecting unload tab on that particular tab not when using commands to unload multiple tabs

**Comment by isiahmeadows** [comment]
@rayman89 That was part of the "force-discard *a particular tab*". 👍

**Comment by rNeomy** [comment]
The context-menu item on tabs context now force-discard the tab. Other methods do respect the conditions.
