### ISSUE TITLE
Suggested wording changes

### ISSUE THREAD

**Issue by Screwtapello** [rNeomy/auto-tab-discard#71]
Firstly, thanks for writing Auto Tab Discard! It's really helped keep my Firefox memory usage down.

However, every time I use the tab context menu, I have to sit and think to decide which option I want, because the name of each option is unfamiliar. Here's what I see now:

* Discard this tab (forced)
* Discard all inactive tabs
* Discard inactive tabs in current window
* Discard inactive tabs in other windows
* Do not discard this domain
* Do not discard for now (session only)

Here are the problems I have:

* Discard this tab (forced)
    * The "(forced)" makes me expect to find a less-forceful "Discard this tab" option somewhere else that I should try first.
    * I suspect this really means "now, instead of waiting for the timer", but the fact that I'm picking this option from a menu automatically implies "do this now", so "(forced)" doesn't really add anything.
* Discard all inactive tabs
    * If I had to guess which tabs were "inactive", I'd say it was tabs already discarded, but it doesn't make much sense to discard already-discarded tabs.
    * It also seems a little odd to put the more general option (...all tabs) before the more specific options (...tabs in current window), but I guess it's more useful..?
* Discard inactive tabs in current window
* Discard inactive tabs in other windows
    * Since discarding a tab shouldn't lose data, it shouldn't be a big deal to discard more tabs than strictly necessary, so maybe these items aren't needed? There's always the "do not discard" options if necessary
* Do not discard this domain
    * Normally picking a menu item triggers an action, or toggles a state, but this text describes *inaction*
    * I suspect this means "permanently", but it doesn't actually say anything about a time-period
* Do not discard for now (session only)
    * Normally "X for now" means "X is true now, but will be false at some unspecified point in the future", but in this case we have a specific and well-defined end-point: the end of the Firefox session.

Here are my suggestions:

* Discard Tab
    * After the model of the regular Firefox "Close Tab" menu item
* Discard Other Tabs in This Window
* Discard Tabs in Other Windows
* Discard All Other Tabs
    * Re-ordered from most-specific to most-general
    * After the model of the regular Firefox "Close Other Tabs" menu item
* Keep Tabs for This Site for This Session
* Always Keep Tabs for This Site
    * Re-ordered from most-specific to most-general
    * Positive phrasing ("keep") is simpler than negative phrasing ("do not discard")
    * Be specific about how long we'll keep tabs
    * Firefox generally refers to per-domain things like cookies and permissions as "per-site"; for example, "Blockable content detected on this site."
    * "Always" is a command with a specific duration, so it fits better as a menu-item
    * It would be even better to put the actual domain instead of "This Site", but I don't know if WebExtensions lets you customise menus to that degree

**Comment by rNeomy** [comment]
Thanks! I agree with all the changes. Here is the new look

![screen shot](https://user-images.githubusercontent.com/14104614/52909983-dad76100-3288-11e9-8b2f-2eb0c6764c68.png)

![screen shot](https://user-images.githubusercontent.com/14104614/52910003-09553c00-3289-11e9-8c70-f6414b78b410.png)

**Comment by Screwtapello** [comment]
Looks great! I'm looking forward to the next release!
