### ISSUE TITLE
Discarded Tab can't reload its link ("Open Link In New Discarded Tab" bug)

### ISSUE THREAD

**Issue by KlausDevWalker** [rNeomy/auto-tab-discard#73]
Usually it happens when you choose "Open Link In New Discarded Tab" in context menu and take a long time to focus on that tab. This kind of tab regularly makes reload button inactive and no URL in the address field. Basically you lost your tab. I've discovered a workaround: when this issue happens, if you right-click the tab and choose "Bookmark tab" you are able to see the URL in Name field (instead of default "Location" field). Then you can copy-paste it on URL field of the browser. I'm using Firefox Quantum 66.0b4 with Windows 10 OS.

![image](https://user-images.githubusercontent.com/3390598/52210762-13ca0b80-286f-11e9-8cc8-0ee3c99cfb79.png)

**Comment by alkumaish** [comment]
This is probably related to #72

**Comment by grahamperrin** [comment]
Not reproducible with Firefox 83: 

![image](https://user-images.githubusercontent.com/192271/101450521-8ea85580-3922-11eb-871e-05978dff1739.png)

– there's a location. 

```text
grahamperrin@mowa219-gjp4-8570p:~ % pkg query '%o %v %R' firefox
www/firefox 83.0_4,2 FreeBSD
grahamperrin@mowa219-gjp4-8570p:~ % date ; uname -v
Tue  8 Dec 2020 05:07:59 GMT
FreeBSD 13.0-CURRENT #72 r367936: Sun Nov 22 21:46:00 GMT 2020     root@mowa219-gjp4-8570p:/usr/obj/usr/src/amd64.amd64/sys/GENERIC-NODEBUG 
```

**Comment by KlausDevWalker** [comment]
> Not reproducible with Firefox 83:
> 
> ![image](https://user-images.githubusercontent.com/192271/101450521-8ea85580-3922-11eb-871e-05978dff1739.png)
> 
> – there's a location.
> 
> ```
> grahamperrin@mowa219-gjp4-8570p:~ % pkg query '%o %v %R' firefox
> www/firefox 83.0_4,2 FreeBSD
> grahamperrin@mowa219-gjp4-8570p:~ % date ; uname -v
> Tue  8 Dec 2020 05:07:59 GMT
> FreeBSD 13.0-CURRENT #72 r367936: Sun Nov 22 21:46:00 GMT 2020     root@mowa219-gjp4-8570p:/usr/obj/usr/src/amd64.amd64/sys/GENERIC-NODEBUG 
> ```

Thanks for the feedback, @grahamperrin. As I'm not a user of Firefox myself right now (and I'm not having this issue with Chrome-based browsers), I'll close this issue. :)
