### ISSUE TITLE
Sync preferences

### ISSUE THREAD

**Issue by marsjaninzmarsa** [rNeomy/auto-tab-discard#74]
It would be nice to synchronize Discarding conditions between Firefox installation - I've just had to set my preferred rules for 10-th time (few machines, some with Dev Edition and Nighlty on dedicated profiles). And it should be optable to allow specific rules for every machine (even as global "don't sync settings with another installations" checkbox).

**Comment by rNeomy** [comment]
True. For now instead of the synced storage, we are going to have two new buttons (import and export preferences) in the options page. The synced storage idea is also a valid point, but it is pretty messy to be implemented.

**Comment by allanlaal** [comment]
for googlers: continued in #102
