### ISSUE TITLE
Documentation alternates between "suspend" and "discard", yet they have different meanings.

### ISSUE THREAD

**Issue by paul-hammant** [rNeomy/auto-tab-discard#77]
Unless I'm mistaken the plugin suspends or does not suspend a tab (dumping the DOM, and memory implications, and unsuspending when the tab is clicked on.

The word "discard", to me, would be one step beyond suspend and actually delete the tab. To go back on that, the user would have to ho into history and click on a line to create a "new" tab for that.

I think the documentation and language within the prefs would be even better if it didn't conflate those two English words :)

**Comment by rNeomy** [comment]
Thanks for the report. Actually, "discard" is the word that is used in the official documentation. So I replaced all the occurrence of the "suspend" word in both extension UI and the doc. Let me know if I've missed any.

See:
https://developer.chrome.com/extensions/tabs#method-discard
https://developers.google.com/web/updates/2015/09/tab-discarding
