### ISSUE TITLE
Discarding and reloading a tab twice breaks "Ctrl-F".

### ISSUE THREAD

**Issue by jimbo1qaz** [rNeomy/auto-tab-discard#8]
Firefox Dev 59.0b3 (64-bit) on Windows 10 64
Extension 0.1.3

* Go to Facebook.com.
* (Begin loop)
* Click to another tab.
* Right-click toolbar icon, "Discard all inactive tabs".
* Click on Facebook tab.
* Loop twice if necessary.
Now Ctrl-F doesn't work anymore.

This happens after discarding and reloading Youtube, htmledit.squarefree.com, xkcd.com, or asdf.com twice.

I have reproduced on a clean profile on https://www.mozilla.org/en-US/privacy/firefox/.

**Comment by rNeomy** [comment]
This seems like an internal API bug. Can you reproduce this on v60 as well?

**Comment by jimbo1qaz** [comment]
Seems fixed (v61 Developer)
