### ISSUE TITLE
Display tooltip, list, or log of tabs and why they were [not] discarded

### ISSUE THREAD

**Issue by cgs2** [rNeomy/auto-tab-discard#80]
When discarding tabs, some appear to be retained despite not obviously matching any rules in the options. It would be very helpful to see which tabs were or were not discarded and the reason why.

**Comment by rNeomy** [comment]
From the next release, the extension is going to update the tooltip for the page that is not being discarded. 

If there is a way to generate this "[not] discarded" situation please provide more info. I'll try to investigate more.

**Comment by hmijail** [comment]
I can't find where this tooltip is supposed to appear. The wording in the FAQ makes me think that this worked on the action buttons that disappeared from Firefox years ago.
