### ISSUE TITLE
strict_min_version in manifest.json, and declarations of compatibility at AMO

### ISSUE THREAD

**Issue by grahamperrin** [rNeomy/auto-tab-discard#83]
Hi

Maybe add a `strict_min_version` to future versions. 

### Context

A Waterfox ~56.2.7.1 shot of the about:addons listing for 0.3.1: 

![image](https://user-images.githubusercontent.com/192271/54728161-2de85080-4b74-11e9-9dd1-4bd628a2e6b5.png)

– there ought to be a yellow alert for incompatibility, but there's not. 

From <https://addons.mozilla.org/addon/auto-tab-discard/>: 

> … `tabs.discard` …

Mozilla bug [1322485 - Implement tabs.discard method for Desktop](https://bugzilla.mozilla.org/show_bug.cgi?id=1322485) was _RESOLVED FIXED in Firefox 58_ so you might like to update the statements of compatibility at https://addons.mozilla.org/addon/auto-tab-discard/versions/ for versions 0.3.0 and 0.3.1, 

> Works with firefox 48.0 and later, android 48.0 and later

Thanks 👍

**Comment by rNeomy** [comment]
Fixed. Thanks for the report.
