### ISSUE TITLE
Visual API needed

### ISSUE THREAD

**Issue by RobertAb1** [rNeomy/auto-tab-discard#85]
Problem description ([source](https://add0n.com/tab-discard.html)):
> RJF:
> Hmmm--does anything visible happen when tabs are discarded--like turning grey, or showing a symbol? I can't seem to get the extension to do anything when I I click to discard all inactive tabs. There are tabs that have been open for several days, using over 1500mb of memory, so I can't imagine that they have been discarded... (...)
>
> Richard:
> The icon of the website should have been changed (if there is no security restriction on the webpage). Unfortunately that all we can do. There is **no visual API** available to change for instance the tab's color or something else.

Question:
**Do you need [Bug 1320585](https://bugzilla.mozilla.org/show_bug.cgi?id=1320585) fixed to get visual API?** Or is there another bug necessary here?

**Comment by rNeomy** [comment]
This looks good to me. The current method that we use is not really trustable. Having a visual API is the best approach.
