### ISSUE TITLE
[Feature request] Loading tabs only after clicking on the page in Firefox

### ISSUE THREAD

**Issue by RobertAb1** [rNeomy/auto-tab-discard#87]
Problem description ([source](https://add0n.com/tab-discard.html)):
> BlayZin:
> Would it be possible to add an option to load tabs only when I actually click on the page like it was in tab supender? often I close a tab and I get put to a discarded one which reloads then and if it is a youtube video for example it is very annoying.
>
> Richard:
> Unfortunately not, **there is no API** for that. As a workaround, you can use the extension's popup buttons for your navigation. If you are on a Chromium browser, you can even set keyboard shortcuts for moving to the first left or right not-discarded tab.

Question:
**Can you file for needed API in Bugzilla** and let me know about bug number?

**Comment by rNeomy** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1554482

**Comment by RobertAb1** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1554482
https://github.com/rNeomy/auto-tab-discard/issues/41
