### ISSUE TITLE
Options don't appear correctly in Firefox add-ons page

### ISSUE THREAD

**Issue by ecbrodie** [rNeomy/auto-tab-discard#90]
I don't believe that the preferences for the add-on are being displayed properly. Specifically, I'm talking about the section that customizes how tabs are discarded (the "period" and "number" options, according to the HTML of that preferences section).

The [Youtube video for your add-on](https://www.youtube.com/watch?v=ityhxUPp3y8) suggests that these should be rendered as radio options, which is how they render in Chrome. But in firefox, it is just one row of text. I have no idea which option is being enabled right now. See below for screenshot (which is in my browser's `about:addons` page):

![Screenshot](https://i.imgur.com/7KSGpGf.png "Screenshot of Firefox Add-ons Page")

**Comment by rNeomy** [comment]
This is actually the correct (new) form. This option means both of these conditions must meet for the discarding to take place.
