### ISSUE TITLE
Favicon for natively discarded tabs

### ISSUE THREAD

**Issue by MOFTAD** [rNeomy/auto-tab-discard#96]
The option to change the favicon of discarded tabs is great; it really helps with distinguishing them from other tabs. Would it be possible to extend the functionality of this option (or include a new option) to cover all discarded tabs (i.e., even those that are discarded by Firefox itself, e.g., upon restoring a session), rather than just those handled by ATD? Thanks for reading.

**Comment by rNeomy** [comment]
It is not doable at the moment. This extension inserts a JS code to draw a new icon just before unloading occurs. Since there is no event for that, it is not possible to extend the behavior.
