### ISSUE TITLE
Add discard tab keyboard shortcut

### ISSUE THREAD

**Issue by sobrinojulian** [rNeomy/auto-tab-discard#98]
btw awesome extension, thanks a lot

**Comment by rNeomy** [comment]
we already have. Go to the extensions manager of your browser;
![Screen Shot](https://user-images.githubusercontent.com/14104614/69247794-f1597280-0ba2-11ea-9d4e-4217aa84826a.png)

**Comment by wulymammoth** [comment]
Great extension, but is this not available in Firefox?

![Screen Shot 2020-07-09 at 9 31 08 AM](https://user-images.githubusercontent.com/861147/87066199-01bc6d00-c1c7-11ea-8ccd-41d9404ef30c.png)

**Comment by rNeomy** [comment]
@wulymammoth 

![Screen Shot 2020-07-18 at 8 04 09 AM](https://user-images.githubusercontent.com/14104614/87846079-aa03bd00-c8bc-11ea-9092-7ce42e573fca.png)
